#include "decap.h"

using namespace std::string_view_literals;

const std::unordered_map<std::string_view, DicEntry> dictionary {
    // Language names
    { "ABKHASIAN",      Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "ADLAM",          Dicf::TRIG_SCRIPT },
    { "AFAKA",          Dicf::TRIG_SCRIPT },
    { "AHOM",           Dicf::TRIG_SCRIPT },
    { "ALBANIAN",       Dicf::TRIG_SCRIPT },
      { "CAUCASIAN",    Dicf::TRIG_SCRIPT },
    { "ALEUT"sv,        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "ANATOLIAN",      Dicf::TRIG_SCRIPT },
    { "APL",            Dicf::CAP_ALL | Dicf::TRIG_SCRIPT },
    { "ARABIC",         Dicf::TRIG_SCRIPT },
    { "ARABIAN",        Dicf::TRIG_SCRIPT },
    { "ARABIC-INDIC",   { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Arabic-Indic"sv } },
    { "ASSAMESE",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::TRIG_FORCE_FULL_DECAP },
    { "IMPERIAL",       Dicf::TRIG_SCRIPT },
    { "ARAMAIC",        Dicf::TRIG_SCRIPT },
    { "ARMENIAN",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "AVESTAN",        Dicf::TRIG_SCRIPT },
    { "BACTRIAN",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "BALINESE",       Dicf::TRIG_SCRIPT },
    { "BAMUM",          Dicf::TRIG_SCRIPT },
    { "BASSA",          Dicf::TRIG_SCRIPT_IF_FIRST }, // Music: bassa = low
      { "VAH",          Dicf::TRIG_SCRIPT },
    { "BATAK",          Dicf::TRIG_SCRIPT },
    { "BENGALI",        Dicf::TRIG_SCRIPT },
    { "VEDIC",          Dicf::CAP_TITLE | Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "BERIA",          { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "ERFE"sv } },
    { "BHAIKSUKI",      Dicf::TRIG_SCRIPT },
    { "BOPOMOFO",       Dicf::TRIG_SCRIPT },
    { "BRAHMI",         Dicf::TRIG_SCRIPT },
    { "BRAILLE",        Dicf::TRIG_SCRIPT },
    { "BUGINESE",       Dicf::TRIG_SCRIPT },
    { "BUHID",          Dicf::TRIG_SCRIPT },
    { "CANADIAN",       Dicf::TRIG_SCRIPT },
    { "CARIAN",         Dicf::TRIG_SCRIPT },
    { "CHAKMA",         Dicf::TRIG_SCRIPT },
    { "CHAM",           Dicf::TRIG_SCRIPT },
    { "CHEROKEE",       Dicf::TRIG_SCRIPT },
    { "CHINESE",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "CHISOI",         Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "CHORASMIAN",     Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "CIRTH",          Dicf::TRIG_SCRIPT },
    { "CJK",            Dicf::CAP_ALL | Dicf::TRIG_SCRIPT },
    { "COPTIC",         Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "CUNEIFORM",      Dicf::TRIG_SCRIPT | Dicf::CAP_SMALL },
    { "CYPRO-MINOAN",   { Dicf::TRIG_SCRIPT, "Cypro-Minoan"sv } },
    { "CYPRIOT",        Dicf::TRIG_SCRIPT },
    { "CYRILLIC",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
      { "KOMI"sv,       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
      { "UKRAINIAN",    Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
      { "BYELORUSSIAN-UKRAINIAN", { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Byelorussian-Ukrainian"sv } },
      { "BASHKIR",      Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "DEVANAGARI",     Dicf::TRIG_SCRIPT },
    { "DOGRA",          Dicf::TRIG_SCRIPT },
    { "DESERET",        Dicf::TRIG_SCRIPT },
    { "DUPLOYAN",       Dicf::TRIG_SCRIPT },
    { "DIVES",          Dicf::TRIG_SCRIPT },
     { "AKURU",         Dicf::TRIG_SCRIPT },
    { "EGYPTIAN",       Dicf::TRIG_SCRIPT },
    { "ELBASAN",        Dicf::TRIG_SCRIPT },
    { "ELYMAIC",        Dicf::TRIG_SCRIPT },
    { "ETHIOPIC",       Dicf::TRIG_SCRIPT },
      { "GURAGE",       Dicf::TRIG_SCRIPT | Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KHUTSURI",       Dicf::TRIG_SCRIPT },    // Unused, but…
    { "FRAKTUR",        Dicf::TRIG_SCRIPT },
    { "GARAY",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "GEORGIAN",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
     { "MTAVRULI",      Dicf::TRIG_SCRIPT },
    { "GONDI",          Dicf::TRIG_SCRIPT },
      { "GUNJALA",      Dicf::TRIG_SCRIPT },
      { "MASARAM",      Dicf::TRIG_SCRIPT },
    { "GOTHIC",         Dicf::TRIG_SCRIPT },
    { "GLAGOLITIC",     Dicf::TRIG_SCRIPT },
    { "GRANTHA",        Dicf::TRIG_SCRIPT },
    { "GREEK",          Dicf::TRIG_SCRIPT_IF_FIRST | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
      { "ATTIC",          Dicf::TRIG_SCRIPT },  // NOT adjective → we use treasure of ignorance here
      { "CARYSTIAN",      Dicf::TRIG_SCRIPT },
      { "CYRENAIC",       Dicf::TRIG_SCRIPT },
      { "DEPLHIC",        Dicf::TRIG_SCRIPT },
      { "EPIDAUREAN",     Dicf::TRIG_SCRIPT },
      { "HERAEUM",        Dicf::TRIG_SCRIPT },
      { "HERMIONIAN",     Dicf::TRIG_SCRIPT },
      { "MESSENIAN",      Dicf::TRIG_SCRIPT },
      { "NAXIAN",         Dicf::TRIG_SCRIPT },
      { "PAMPHYLIAN",     Dicf::TRIG_SCRIPT },
      { "STRATIAN",       Dicf::TRIG_SCRIPT },
      { "THESPIAN",       Dicf::TRIG_SCRIPT },
      { "TROEZENIAN",     Dicf::TRIG_SCRIPT },
    { "GUJARATI",       Dicf::TRIG_SCRIPT },
    { "GURMUKHI",       Dicf::TRIG_SCRIPT },
    { "GURUNG",         Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
      { "KHEMA",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "HANGUL",         Dicf::TRIG_SCRIPT },
    { "HANIFI",         Dicf::TRIG_SCRIPT },
     { "ROHINGYA",      Dicf::TRIG_SCRIPT },
    { "HANGZHOU",       Dicf::TRIG_SCRIPT },
    { "HANUNOO",        Dicf::TRIG_SCRIPT },
    { "HATRAN",         Dicf::TRIG_SCRIPT },
    { "HEBREW",         Dicf::TRIG_SCRIPT },
    { "HIRAGANA",       Dicf::TRIG_SCRIPT },
    { "HENTAIGANA",     Dicf::TRIG_SCRIPT },
    { "HUNGARIAN",      Dicf::TRIG_SCRIPT },
    { "INDIC",          Dicf::TRIG_SCRIPT },
    { "INDUS",          Dicf::TRIG_SCRIPT },
    { "JAPANESE",       Dicf::TRIG_SCRIPT },
    { "JAVANESE",       Dicf::TRIG_SCRIPT },
    { "JUDEO-SPANISH",  { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Judeo-Spanish" } },
    { "JURCHEN",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "KAKTOVIK",       Dicf::TRIG_SCRIPT },
    { "KANGXI",         Dicf::TRIG_SCRIPT },
    { "KANNADA",        Dicf::TRIG_SCRIPT },
    { "KATAKANA",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "KATAKANA-HIRAGANA", { Dicf::TRIG_SCRIPT, "Katakana-Hiragana"sv } },
    { "KAWI",           Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "KAYAH",          { Dicf::TRIG_TWO_WORD_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE, {}, "LI"sv } },
    { "KHAROSHTHI",     Dicf::TRIG_SCRIPT },
    { "KHMER",          Dicf::TRIG_SCRIPT },
    { "KHOJKI",         Dicf::TRIG_SCRIPT },
    { "KHITAN",         Dicf::TRIG_SCRIPT },
    { "KHUDAWADI",      Dicf::TRIG_SCRIPT },
    { "KIRAT",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
      { "RAI",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "KLINGON",        Dicf::TRIG_SCRIPT },
    { "KOREAN",         Dicf::TRIG_SCRIPT },
    { "KPELLE",         Dicf::TRIG_SCRIPT },
    { "KAITHI",         Dicf::TRIG_SCRIPT },
    { "LAO",            Dicf::TRIG_SCRIPT },
    { "LATIN",          Dicf::TRIG_SCRIPT },
    { "LEKE",           Dicf::TRIG_SCRIPT },
    { "LEPCHA",         Dicf::TRIG_SCRIPT },
    { "LIMBU",          Dicf::TRIG_SCRIPT },
    { "LINEAR",         { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "A"sv, "B"sv } },
    { "LISU",           Dicf::TRIG_SCRIPT },
    { "LOMA",           Dicf::TRIG_SCRIPT },
    { "LYCIAN",         Dicf::TRIG_SCRIPT },
    { "LYDIAN",         Dicf::TRIG_SCRIPT },
    { "MAHAJANI",       Dicf::TRIG_SCRIPT },
    { "MAKASAR",        Dicf::TRIG_SCRIPT },
    { "MALAYALAM",      Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "MALTESE",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "MANDAIC",        Dicf::TRIG_SCRIPT },
    { "MANDAEAN",       Dicf::TRIG_SCRIPT },
    { "MANICHAEAN",     Dicf::TRIG_SCRIPT },
    { "MARCHEN",        Dicf::TRIG_SCRIPT },
    { "MAYAN",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "MEDEFAIDRIN",    Dicf::TRIG_SCRIPT },
    { "MEETEI",         Dicf::TRIG_SCRIPT },
      { "MAYEK",        Dicf::TRIG_SCRIPT },
    { "MENDE",          Dicf::TRIG_SCRIPT | Dicf::TRIG_DIGIT_PROPAGATES_RIGHT },
      { "KIKAKUI",      Dicf::TRIG_SCRIPT | Dicf::TRIG_DIGIT_PROPAGATES_RIGHT },
    { "MEROITIC",       Dicf::TRIG_SCRIPT },
    { "MIAO",           Dicf::TRIG_SCRIPT },
    { "MIDDLE-WELSH",   { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Middle-Welsh" } },
    { "MODI",           Dicf::TRIG_SCRIPT },
    { "MONGOLIAN",      Dicf::TRIG_SCRIPT },
    { "MRO",            Dicf::TRIG_SCRIPT },
    { "MULTANI",        Dicf::TRIG_SCRIPT },
    { "MYANMAR",        Dicf::TRIG_SCRIPT },
    { "NABATAEAN",      Dicf::TRIG_SCRIPT },
    { "NANDINAGARI",    Dicf::TRIG_SCRIPT },
    { "NEWA",           Dicf::TRIG_SCRIPT },
    { "NKO",            { Dicf::TRIG_SCRIPT, "NKo" } },
    { "NUBIAN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "NUSHU",          Dicf::TRIG_SCRIPT },
    { "OGHAM",          Dicf::TRIG_SCRIPT },
    { "OL",             { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "CHIKI"sv, "ONAL"sv } },
    { "OTTOMAN",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "TURKIC",         Dicf::TRIG_SCRIPT },
    { "ORIYA",          Dicf::TRIG_SCRIPT },
    { "OSAGE",          Dicf::TRIG_SCRIPT },
    { "OSMANYA",        Dicf::TRIG_SCRIPT },
    { "PAHAWH",         Dicf::TRIG_SCRIPT },
      { "HMONG",          Dicf::TRIG_SCRIPT },
      { "NYIAKENG",      Dicf::TRIG_SCRIPT },
      { "PUACHUE",       Dicf::TRIG_SCRIPT },
    { "PAHLAVI",        Dicf::TRIG_SCRIPT },
    { "PALI",           Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "PALMYRENE",      Dicf::TRIG_SCRIPT },
    { "PARTHIAN",       Dicf::TRIG_SCRIPT },
    { "PAU",            { Dicf::TRIG_THREE_WORD_SCRIPT, {}, "CIN"sv, "HAU"sv } },
    { "PERSIAN",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "PHAISTOS",       { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "DISC" } },
    { "PHAGS-PA",       Dicf::TRIG_SCRIPT },
    { "PHOENICIAN",     Dicf::TRIG_SCRIPT },
    { "PHILIPPINE",     Dicf::TRIG_SCRIPT },
    { "REJANG",         Dicf::TRIG_SCRIPT },
    { "ROMAN",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "RONGORONGO",     Dicf::TRIG_SCRIPT },
    { "RUNIC",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_SMALL },
    { "SAMARITAN",      Dicf::TRIG_SCRIPT },
    { "SANSKRIT",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "SARATI",         Dicf::TRIG_SCRIPT },
    { "SAUDI",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SAURASHTRA",     Dicf::TRIG_SCRIPT },
    { "SCOTS",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "SHAVIAN",        Dicf::TRIG_SCRIPT },
    { "SHARADA",        Dicf::TRIG_SCRIPT },
    { "SHUISHU",        Dicf::TRIG_SCRIPT },
    { "SIDDHAM",        Dicf::TRIG_SCRIPT },
    { "SIDETIC",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "SIGNWRITING",    { Dicf::PART_NOUN | Dicf::TRIG_SCRIPT, "SignWriting" } },
    { "SINHALA",        Dicf::TRIG_SCRIPT },
    { "SIYAQ",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "SORA",           { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "SOMPENG"sv } },
    { "SOYOMBO",        Dicf::TRIG_SCRIPT },
    { "SUNDANESE",      Dicf::TRIG_SCRIPT },
    { "SUNUWAR",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "SYLOTI",         Dicf::TRIG_SCRIPT },
    { "NAGRI",          Dicf::TRIG_SCRIPT },
    { "SOGDIAN",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "SYRIAC",         Dicf::TRIG_SCRIPT },
    { "TAGALOG",        Dicf::TRIG_SCRIPT },
    { "TAGBANWA",       Dicf::TRIG_SCRIPT },
    { "TAKRI",          Dicf::TRIG_SCRIPT },
    { "TAMIL",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "TANGSA",         Dicf::TRIG_SCRIPT },
    { "TANGUT",         Dicf::TRIG_SCRIPT },
    { "TELUGU",         Dicf::TRIG_SCRIPT },
    { "TENGWAR",        Dicf::TRIG_SCRIPT },
    { "TIFINAGH",       Dicf::TRIG_SCRIPT },
     { "AHAGGAR",       Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
     { "TUAREG",        Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
     { "TAWELLEMET",    Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
     { "AYER",          Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "THAANA",         Dicf::TRIG_SCRIPT },
    { "THAI",           Dicf::TRIG_SCRIPT },
    { "TIBETAN",        Dicf::TRIG_SCRIPT },
    { "TIRHUTA",        Dicf::TRIG_SCRIPT },
    { "TODHRI",         Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE },
    { "TOLONG",         { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "SIKI"sv } },
    { "TOTO",           Dicf::TRIG_SCRIPT },
    { "TULU-TIGALARI",  { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Tulu-Tigalari" } },
    { "UIGHUR",         Dicf::TRIG_SCRIPT | Dicf::CAP_TITLE },
    { "UYGHUR",         Dicf::TRIG_SCRIPT | Dicf::CAP_TITLE },
    { "UGARITIC",       Dicf::TRIG_SCRIPT },
    { "VAI",            Dicf::TRIG_SCRIPT },
    { "VIETNAMESE",     Dicf::TRIG_SCRIPT | Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "VITHKUQI",       Dicf::TRIG_SCRIPT },
    { "WARANG",         { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "CITI"sv } },
    { "WANCHO",         Dicf::TRIG_SCRIPT },
    { "YEZIDI"sv,       Dicf::TRIG_SCRIPT },
    { "YI"sv,           Dicf::TRIG_SCRIPT_IF_FIRST },
    { "ZANABAZAR",      Dicf::TRIG_SCRIPT },
    { "ZNAMENNY",       Dicf::TRIG_SCRIPT },

    { "OCR",            Dicf::CAP_ALL },
    { "MICR",           Dicf::CAP_ALL },
    { "ARIB",           Dicf::CAP_ALL },
    { "STD",            Dicf::CAP_ALL },
    { "B24",            Dicf::CAP_ALL },
    { "MIDI",           Dicf::CAP_ALL },
    { "ATM",            Dicf::CAP_ALL },
    { "ROFL",           Dicf::CAP_ALL },
    { "ROTFL",          Dicf::CAP_ALL },
    { "HDTV",           Dicf::CAP_ALL },
    { "SDTV",           Dicf::CAP_ALL },
    { "UFO",            Dicf::CAP_ALL },

    // Special adjectives
    { "EASTERN",        { Dicf::TRIG_TWO_WORD_SCRIPT | Dicf::PART_ADJECTIVE,
                          {}, "PWO" } },
    // There are several NAGs → it’s script only with Mundari
    { "NAG",            { Dicf::TRIG_TWO_WORD_SCRIPT | Dicf::PART_ADJECTIVE,
                          {}, "MUNDARI" } },
    // Interesting case: ITALIC is script with OLD only
    // For ARABIAN we can use just SCRIPT_ADJECTIVE, it’s enough to identify script
    { "OLD",            { Dicf::PART_ADJECTIVE | Dicf::TRIG_TWO_WORD_SCRIPT | Dicf::TRIG_SCRIPT_ADJECTIVE,
                          {}, "ITALIC", "PERMIC", "PERSIAN" } },
    { "TAI",            { Dicf::TRIG_TWO_WORD_SCRIPT, {}, "LE"sv, "VIET"sv, "THAM"sv, "LAING"sv, "YO"sv } },
      { "LAING",        Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::IF_NEXT_NOT_NOUN },

    // Capitalize next
    { "AFFIX",          Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "ACROPHONIC",     Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "CHARACTER",      Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "CHOSEONG",       Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
      { "JUNGSEONG",    Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
      { "JONGSEONG",    Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "DENOMINATOR",    Dicf::PART_NOUN | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "DIGIT",          Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL  },
    { "FRACTION",       Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "HIEROGLYPH",     Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "IDEOGRAM",       Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "LETTER",         Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "DIGRAPH",        Dicf::TRIG_CAP_NEXT | Dicf::PART_NOUN | Dicf::CAP_SMALL },
    { "LIGATURE",       Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "LOGICAL",        Dicf::TRIG_CAP_NEXT },
    { "LOGOGRAM",       Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "MARK",           Dicf::PART_NOUN | Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "MODIFIER",       Dicf::TRIG_CAP_NEXT | Dicf::PART_NOUN | Dicf::CAP_SMALL },
    { "NEUME",          Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "NUMBER",         Dicf::PART_NOUN | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "NUMERAL",        Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "NUMERATOR",      Dicf::PART_NOUN | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "PADA",           Dicf::IF_SCRIPT | Dicf::PART_NOUN | Dicf::TRIG_CAP_NEXT },
    { "PATTERN",        Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "PUNCTUATION",    Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "RADICAL",        Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "SIGN",           Dicf::PART_NOUN | Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "SYMBOL",         Dicf::PART_NOUN | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "SYLLABICS",      Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "SYLLABLE",       Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },
    { "VOWEL",          Dicf::IF_SCRIPT | Dicf::TRIG_CAP_NEXT | Dicf::CAP_SMALL },

    // Mixed
    { "TONE",           Dicf::PART_MIXED | Dicf::TRIG_CAP_NEXT | Dicf::IF_SCRIPT | Dicf::IF_NEXT_NOT_NOUN },
    { "REPETITION",     Dicf::PART_MIXED | Dicf::TRIG_CAP_NEXT | Dicf::IF_SCRIPT | Dicf::IF_NEXT_NOT_NOUN },
    { "WORD",           Dicf::PART_MIXED | Dicf::TRIG_CAP_NEXT | Dicf::IF_SCRIPT | Dicf::IF_NEXT_NOT_NOUN },

    // American tribes
    { "AIVILIK",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "ATHAPASCAN",     Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "BLACKFOOT",      Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
      // Who knows what to do with Carrier (Canadian tribe)
    { "CARRIER",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT },
      // CREE here
      { "BIBLE-CREE",   { Dicf::PART_ADJECTIVE, "Bible-Cree" } },
      { "MOOSE-CREE",   { Dicf::PART_ADJECTIVE, "Moose-Cree" } },
      { "N-CREE",       { Dicf::PART_ADJECTIVE, "N-Cree" } },
      { "R-CREE",       { Dicf::PART_ADJECTIVE, "R-Cree" } },
      { "TH-CREE",      { Dicf::PART_ADJECTIVE, "Th-Cree" } },
      { "WEST-CREE",    { Dicf::PART_ADJECTIVE, "West-Cree" } },
      { "WOODS-CREE",   { Dicf::TRIG_SCRIPT | Dicf::PART_ADJECTIVE, "Woods-Cree" } },
      { "Y-CREE",       { Dicf::PART_ADJECTIVE, "Y-Cree" } },
    { "DENE",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT },
    { "NASKAPI",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "NATTILIK",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "NUNAVIK",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "OJIBWAY",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SAYISI",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SOUTH-SLAVEY",   { Dicf::PART_ADJECTIVE, "South-Slavey" } },

    // Myanmar nations
    { "AITON",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KAREN",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
      // KAYAH (above)
    { "KHAMTI",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "MON",            Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "PALAUNG",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "PAO",            Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "PWO",            Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "RUMAI",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SGAW",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SHAN",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
      { "COUNCIL",      Dicf::CAP_TITLE | Dicf::PART_MIXED },
    { "SHWE",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },

    // Mongolian nations/alphabets
    { "ALI",            Dicf::PART_ADJECTIVE },
    { "GALI",           Dicf::CAP_SMALL | Dicf::TRIG_CAP_NEXT },
    { "MANCHU",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SIBE",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "TODO",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },

    // Indonesian nations
    { "KARO",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "MANDAILING",     Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "PAKPAK",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SIMALUNGUN",     Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },

    // Other nations
    { "AEGEAN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "AFRICAN",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "AKHMIMIC",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "AMERICAN",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "ASSYRIAN",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "BOHAIRIC",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "BYZANTINE",      Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "CORNISH",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "ELAMITE",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "EUROPEAN",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "FRENCH",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "GERMAN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "HARKLEAN",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "INDIAN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "JAIN",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KASHMIRI",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KAZAKH",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KHAKASSIAN",     Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "KIRGHIZ",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "NORDIC",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "OMANI",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "ORKHON",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "RUSSIAN",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SAKHA",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SEBATBEIT",      Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SLAVONIC",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "TURKISH",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "UAE",            Dicf::CAP_ALL | Dicf::PART_ADJECTIVE },
    { "VULCAN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },

    // Nouns
    { "ANUSVARA",       Dicf::PART_NOUN },
    { "APOSTROPHE",     Dicf::PART_NOUN },
    { "ARDHAVISARGA",   Dicf::PART_NOUN },
    { "ASPIRATION",     Dicf::PART_NOUN },
    { "AXE",            Dicf::PART_NOUN },  // For Phaistos Disc
    { "ARROW",          Dicf::PART_NOUN },
    { "ARROWHEAD",      Dicf::PART_NOUN },
    { "BALUDA",         Dicf::PART_NOUN },
    { "BAR",            Dicf::PART_NOUN },
    { "BARB",           Dicf::PART_NOUN },
    { "BEAT",           Dicf::PART_NOUN },
    { "BHALE",          Dicf::PART_NOUN },
    { "BIRD",           Dicf::PART_NOUN },  // For some CJK hiero
    { "BOX",            Dicf::PART_NOUN },
    { "BRDA",           Dicf::PART_NOUN },
    { "CANDRABINDU",    Dicf::PART_NOUN },
    { "CARET",          Dicf::PART_NOUN },  // For APL not really, but OK
    { "CIRCLE",         Dicf::PART_NOUN },
    { "CLICK",          Dicf::PART_NOUN },
    { "COLON",          Dicf::PART_NOUN },
     { "TRICOLON",      Dicf::PART_NOUN },
     { "QUADCOLON",     Dicf::PART_NOUN },
    { "COMMA",          Dicf::PART_NOUN },
    { "CROSS",          Dicf::PART_NOUN },
    { "DAMARU",         Dicf::PART_NOUN },
    { "DANDA",          Dicf::PART_NOUN },
    { "DIVIDER",        Dicf::PART_NOUN },
    { "DNA",            Dicf::PART_NOUN | Dicf::CAP_ALL },
    { "DOT",            Dicf::PART_NOUN },
    { "DOTS",           Dicf::PART_NOUN },
    { "DVD",            Dicf::PART_NOUN | Dicf::CAP_ALL },
    { "FORM",           Dicf::PART_NOUN },
    { "HAMZA",          Dicf::PART_NOUN },  // Arabic, not really letter
    { "HASANTA",        Dicf::PART_NOUN },
    { "HOOK",           Dicf::PART_NOUN },
    { "HYPHEN",         Dicf::PART_NOUN },
    { "LINE",           Dicf::PART_NOUN },
    { "MACRON",         Dicf::PART_NOUN },
    { "MCHU",           Dicf::PART_NOUN },
    { "MOON-JUPITER",   { Dicf::PART_NOUN, "moon-Jupiter" } },
    { "MUCAAD",         Dicf::PART_NOUN },
    { "NUKTA",          Dicf::PART_NOUN },
    { "OMET",           Dicf::PART_NOUN },  // Znamenny, for adj “Curved”
    { "PLUS",           Dicf::PART_NOUN },
    { "PRIME",          Dicf::PART_NOUN },
    { "RANA",           Dicf::PART_NOUN },
    { "REDUPLICATION",  Dicf::PART_NOUN },
    { "RIKRIK",         Dicf::PART_NOUN },
    { "RING",           Dicf::PART_NOUN },
    { "SCRUPLE",        Dicf::PART_NOUN },
    { "SECANT",         Dicf::PART_NOUN },
    { "SECTION",        Dicf::PART_NOUN },
    { "SEPARATOR",      Dicf::PART_NOUN },
    { "SHAD",           Dicf::PART_NOUN },
    { "SHELF",          Dicf::PART_NOUN },
    { "SHOE",           Dicf::PART_NOUN },  // For APL not really, but OK
    { "SHRII",          Dicf::PART_NOUN | Dicf::CAP_TITLE }, // That’s for Indic, near miss but OK in Cans
    { "SPIRAL",         Dicf::PART_NOUN },
    { "SPIRANT",        Dicf::PART_NOUN },  // One time, probably OK
    { "STEM",           Dicf::PART_NOUN },
    { "STOP",           Dicf::PART_NOUN },
    { "STRESS",         Dicf::PART_NOUN },  // For music, seemingly OK in other chars
    { "STROKE",         Dicf::PART_NOUN },
    { "STROKES",        Dicf::PART_NOUN },
    { "SVARITA",        Dicf::PART_NOUN },
    { "T-REX",          Dicf::PART_NOUN | Dicf::CAP_TITLE },
    { "T-SHIRT",        Dicf::PART_NOUN | Dicf::CAP_TITLE },
    { "TACK",           Dicf::PART_NOUN },
    { "TREE",           Dicf::PART_NOUN },
    { "TSHEG",          Dicf::PART_NOUN },
    { "UBADAMA",        Dicf::PART_NOUN },
    { "UNDERBAR",       Dicf::PART_NOUN },
    { "UNSTRESS",       Dicf::PART_NOUN },
    { "VARIKA",         Dicf::PART_NOUN },
    { "VIRAMA",         Dicf::PART_NOUN },
    { "VISARGA",        Dicf::PART_NOUN },
    { "VOICING",        Dicf::PART_NOUN },
    { "WAVE",           Dicf::PART_NOUN },
    { "X-RAY",          Dicf::PART_NOUN | Dicf::CAP_TITLE },
    { "X-X",            Dicf::PART_NOUN | Dicf::CAP_ALL },
    { "YANG",           Dicf::PART_MIXED },  // for Chinese tones, need more things
    //{ "YAT",            Dicf::PART_NOUN }, // Yat is normal (Capitalized)…
    { "YIG",            Dicf::PART_NOUN },
    { "YIN",            Dicf::PART_NOUN },   // for Chinese tones, seems to be OK
    { "YUS",            Dicf::PART_NOUN },   // …but yus is big & little → do not cap

    // Greek
#define GREK(x) { x, Dicf::PART_NOUN | Dicf::CAP_TITLE },
    GREK("ALPHA")
    GREK("BETA")
    GREK("GAMMA")
      GREK("DIGAMMA")
    GREK("DELTA")
    GREK("EPSILON")
    GREK("ZETA")
    GREK("ETA")
    GREK("THETA")
    GREK("IOTA")
    GREK("KAPPA")
    GREK("LAMDA")
    GREK("LAMBDA")
    GREK("MU")
    GREK("NU")
    GREK("XI")
    GREK("OMICRON")
    GREK("PI")
    GREK("RHO")
    GREK("THETA")
    GREK("SIGMA")
    GREK("TAU")
    GREK("UPSILON")
    GREK("PHI")
    GREK("CHI")
    GREK("PSI")
    GREK("OMEGA")
    GREK("NABLA")
#undef GREK

    // Tricky but work as noun
    { "PERCUSSIVE",     Dicf::PART_NOUN },

    // Adverbs
    { "ABOVE",          Dicf::PART_NOUN },
    { "BELOW",          Dicf::PART_NOUN },

    // Control abbreviations
    { "(FF)",           Dicf::CAP_ALL },
    { "(LF)",           Dicf::CAP_ALL },
    { "(CR)",           Dicf::CAP_ALL },

    // Numerals
    { "ONE",            Dicf::PART_NUMERAL },
    { "TWO",            Dicf::PART_NUMERAL },
    { "THREE",          Dicf::PART_NUMERAL },
    { "FOUR",           Dicf::PART_NUMERAL },
    { "FIVE",           Dicf::PART_NUMERAL },
    { "SIX",            Dicf::PART_NUMERAL },
    { "SEVEN",          Dicf::PART_NUMERAL },
    { "EIGHT",          Dicf::PART_NUMERAL },
    { "EIGHTH",         Dicf::PART_NUMERAL },
    { "NINE",           Dicf::PART_NUMERAL },
    { "TEN",            Dicf::PART_NUMERAL },
    { "ELEVEN",         Dicf::PART_NUMERAL },
    { "TWELVE",         Dicf::PART_NUMERAL },
    { "FORTY",          Dicf::PART_NUMERAL },
    { "FIFTY",          Dicf::PART_NUMERAL },

    // Numeric tones are nouns
    { "TONE-1",         Dicf::PART_NOUN },
    { "TONE-2",         Dicf::PART_NOUN },
    { "TONE-3",         Dicf::PART_NOUN },
    { "TONE-4",         Dicf::PART_NOUN },
    { "TONE-5",         Dicf::PART_NOUN },
    { "TONE-6",         Dicf::PART_NOUN },
    { "TONE-7",         Dicf::PART_NOUN },
    { "TONE-8",         Dicf::PART_NOUN },
    { "TONE-9",         Dicf::PART_NOUN },
    { "TONE-B",         Dicf::PART_NOUN },
    { "TONE-D",         Dicf::PART_NOUN },
    { "TONE-G",         Dicf::PART_NOUN },
    { "TONE-J",         Dicf::PART_NOUN },
    { "TONE-M",         Dicf::PART_NOUN },
    { "TONE-S",         Dicf::PART_NOUN },

    // Numeric marks are nouns
    { "MARK-1",         Dicf::PART_NOUN },
    { "MARK-2",         Dicf::PART_NOUN },
    { "MARK-3",         Dicf::PART_NOUN },
    { "MARK-4",         Dicf::PART_NOUN },
    { "MARK-5",         Dicf::PART_NOUN },
    { "MARK-6",         Dicf::PART_NOUN },
    { "MARK-7",         Dicf::PART_NOUN },
    { "MARK-8",         Dicf::PART_NOUN },
    { "MARK-9",         Dicf::PART_NOUN },

    // Musical nouns
    { "ACCENT",         Dicf::PART_NOUN },
    { "ACCENT-STACCATO", Dicf::PART_NOUN },
    { "BARLINE",        Dicf::PART_NOUN },
    { "BOW",            Dicf::PART_NOUN },
    { "DOIT",           Dicf::PART_NOUN },
    { "FERMATA",        Dicf::PART_NOUN },
    { "FLAG-1",         Dicf::PART_NOUN },
    { "FLAG-2",         Dicf::PART_NOUN },
    { "FLAG-3",         Dicf::PART_NOUN },
    { "FLAG-4",         Dicf::PART_NOUN },
    { "FLAG-5",         Dicf::PART_NOUN },
    { "FLAG-6",         Dicf::PART_NOUN },
    { "FLAG-7",         Dicf::PART_NOUN },
    { "FLAG-8",         Dicf::PART_NOUN },
    { "FLIP",           Dicf::PART_NOUN },
    { "HARMONIC",       Dicf::PART_NOUN },      // OK, music only
    { "LOURE",          Dicf::PART_NOUN },
    { "MARCATO",        Dicf::PART_NOUN },
    { "MARCATO-STACCATO", Dicf::PART_NOUN },
    { "NOTE",           Dicf::PART_NOUN },
    { "PIZZICATO",      Dicf::PART_NOUN },
    { "REST",           Dicf::PART_NOUN },
    { "RIP",            Dicf::PART_NOUN },
    { "STACCATISSIMO",  Dicf::PART_NOUN },
    { "STACCATO",       Dicf::PART_NOUN },
    { "TENUTO",         Dicf::PART_NOUN },
    { "TONGUE",         Dicf::PART_NOUN },      // OK, never used as adjective
    { "TREMOLO-1",      Dicf::PART_NOUN },
    { "TREMOLO-2",      Dicf::PART_NOUN },
    { "TREMOLO-3",      Dicf::PART_NOUN },
    { "TREMOLO-4",      Dicf::PART_NOUN },
    { "TREMOLO-5",      Dicf::PART_NOUN },
    { "TURN",           Dicf::PART_NOUN },

    // Adjectives
    { "ACUTE",          Dicf::PART_ADJECTIVE },
    { "ALTERNATE",      Dicf::PART_ADJECTIVE },
    { "ALTERNATIVE",    Dicf::PART_ADJECTIVE },
    { "ALVEOLAR",       Dicf::PART_ADJECTIVE },
    { "ARCHAIC",        Dicf::PART_ADJECTIVE },
    { "ARKTIKO",        Dicf::PART_ADJECTIVE },
    { "ASPIRATED",      Dicf::PART_ADJECTIVE },
    { "ATACHED",        Dicf::PART_ADJECTIVE },
    { "BARRED",         Dicf::PART_ADJECTIVE },
    { "BIG",            Dicf::PART_ADJECTIVE },
    { "BIDENTAL",       Dicf::PART_ADJECTIVE },
    { "BILABIAL",       Dicf::PART_ADJECTIVE },
    { "BREATHY",        Dicf::PART_ADJECTIVE },
    { "BOOK",           Dicf::PART_ADJECTIVE },
    { "BOTTOM",         Dicf::PART_ADJECTIVE },
    { "C-SIMPLIFIED",   Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "CAPITAL",        Dicf::PART_ADJECTIVE },
    { "CARTESIAN",      Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "CASKET",         Dicf::PART_ADJECTIVE }, // OK here, runes
    { "CHILLU",         Dicf::PART_ADJECTIVE }, // used for Malayalam
    { "CIRCLED",        Dicf::PART_ADJECTIVE | Dicf::CAP_SMALL },
    { "CLOSED",         Dicf::PART_ADJECTIVE },
    { "CLOSING",        Dicf::PART_ADJECTIVE },
    { "COMBINING",      Dicf::PART_ADJECTIVE },
    { "CROSSED",        Dicf::PART_ADJECTIVE },
    { "CRYPTOGRAMMIC",  Dicf::PART_ADJECTIVE },
    { "CURLED",         Dicf::PART_ADJECTIVE },
    { "CURVED",         Dicf::PART_ADJECTIVE },
    { "DENTAL",         Dicf::PART_ADJECTIVE },
    { "DIGRAMMA",       Dicf::PART_ADJECTIVE }, // Not really an adj, but works so
    { "DOUBLE",         Dicf::PART_ADJECTIVE },
    { "DOUBLE-STRUCK",  Dicf::PART_ADJECTIVE },
    { "DOTTED",         Dicf::PART_ADJECTIVE },
    { "DOTLESS",        Dicf::PART_ADJECTIVE },
    { "DOWN",           Dicf::PART_ADJECTIVE },
    { "DIAERESIZED",    Dicf::PART_ADJECTIVE },
    { "DIAGONAL",       Dicf::PART_ADJECTIVE },
    { "DIALECT-P",      { Dicf::PART_ADJECTIVE, "dialect-P" } },
    { "DIPHTHONG",      Dicf::PART_ADJECTIVE },  // Noun but works
    { "EGYPTOLOGICAL",  Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "EPENTHETIC",     Dicf::PART_ADJECTIVE },
    { "EXCLAMATION",    Dicf::PART_ADJECTIVE },
    { "FINGERED",       Dicf::PART_ADJECTIVE },
    { "FIVE-LIKE",      Dicf::PART_ADJECTIVE },
    { "FIXED-FORM",     Dicf::PART_ADJECTIVE },
    { "FINAL",          Dicf::PART_ADJECTIVE },
    { "FLAT",           Dicf::PART_ADJECTIVE },
    { "FLATTENED",      Dicf::PART_ADJECTIVE },
    { "FRICATIVE",      Dicf::PART_ADJECTIVE },
    { "GLOTTAL",        Dicf::PART_ADJECTIVE },
    { "GRAVE",          Dicf::PART_ADJECTIVE },
    { "GREAT",          Dicf::PART_ADJECTIVE },
    { "HALF",           Dicf::PART_ADJECTIVE },
    { "HARD",           Dicf::PART_ADJECTIVE },
    { "HEAVY",          Dicf::PART_ADJECTIVE },
    { "HIGH",           Dicf::PART_ADJECTIVE },
    { "HORIZONTAL",     Dicf::PART_ADJECTIVE },
    { "IOTATED",        Dicf::PART_ADJECTIVE },
    { "IOTIFIED",       Dicf::PART_ADJECTIVE },
    { "INHERENT",       Dicf::PART_ADJECTIVE },
    { "INITIAL",        Dicf::PART_ADJECTIVE },
    { "INSCRIPTIONAL",  Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT_ADJECTIVE },
    { "INSULAR",        Dicf::PART_ADJECTIVE },
    { "INVERTED",       Dicf::PART_ADJECTIVE },
    { "J-SIMPLIFIED",   Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "JONA",           Dicf::PART_ADJECTIVE },     // Nkoo, probably small
    { "KINNA",          Dicf::PART_ADJECTIVE },     // Rohg, kinna = small
    { "LARYNGEAL",      Dicf::PART_ADJECTIVE },
    { "LATERAL",        Dicf::PART_ADJECTIVE },
    { "LATINATE",       Dicf::PART_ADJECTIVE },
    { "LAZY",           Dicf::PART_ADJECTIVE },
    { "LEFT",           Dicf::PART_ADJECTIVE },
    { "LEFT-STEM",      Dicf::PART_ADJECTIVE },
    { "LEIBNIZIAN",     Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "LIGATING",       Dicf::PART_ADJECTIVE },
    { "LONG",           Dicf::PART_ADJECTIVE },
    { "LONG-LEGGED",    Dicf::PART_ADJECTIVE },
    { "LOOPED",         Dicf::PART_ADJECTIVE },
    { "LOST",           Dicf::PART_ADJECTIVE },
    { "LOW",            Dicf::PART_ADJECTIVE },
    { "LUNATE",         Dicf::PART_ADJECTIVE },
    { "LITTLE",         Dicf::PART_ADJECTIVE },
    { "MARWARI",        Dicf::PART_ADJECTIVE },
    { "MEDIAL",         Dicf::PART_ADJECTIVE },
    { "MID",            Dicf::PART_ADJECTIVE },
    { "MIDDLE",         Dicf::PART_ADJECTIVE },
    { "MONOCULAR",      Dicf::PART_ADJECTIVE },     // Cyrl
    { "MONOGRAPH",      Dicf::PART_ADJECTIVE },
    { "MULTIOCULAR",    Dicf::PART_ADJECTIVE },     // Cyrl
    { "NASAL",          Dicf::PART_ADJECTIVE },
    { "NDOLE",          Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },   // Vai
    { "NEUTRAL",        Dicf::PART_ADJECTIVE },
    { "NEW",            { Dicf::PART_ADJECTIVE | Dicf::TRIG_THREE_WORD_SCRIPT, {}, "TAI"sv, "LUE"sv, }},
    { "NINE-LIKE",      Dicf::PART_ADJECTIVE },
    // Old NORTH Arabian
    { "NORTH",          Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT_ADJECTIVE },
    { "NORTHERN",       Dicf::PART_ADJECTIVE },
    { "OBLIQUE",        Dicf::PART_ADJECTIVE },
    { "OPEN",           Dicf::PART_ADJECTIVE },
    { "OVERLONG",       Dicf::PART_ADJECTIVE },
    { "PALATAL",        Dicf::PART_ADJECTIVE },
    { "PHARYNGEAL",     Dicf::PART_ADJECTIVE },
    { "PHASE-A",        { Dicf::PART_ADJECTIVE, "phase-A" } },
    { "PHASE-B",        { Dicf::PART_ADJECTIVE, "phase-B" } },
    { "PHASE-C",        { Dicf::PART_ADJECTIVE, "phase-C" } },
    { "PHASE-D",        { Dicf::PART_ADJECTIVE, "phase-D" } },
    { "PHASE-E",        { Dicf::PART_ADJECTIVE, "phase-E" } },
    { "PHASE-F",        { Dicf::PART_ADJECTIVE, "phase-F" } },
    { "PHONOTYPIC",     Dicf::PART_ADJECTIVE },
    { "PSALTER",        Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT_ADJECTIVE },
    { "QUARTER",        Dicf::PART_ADJECTIVE }, // Not really OK, but works somehow
    { "REFORMED",       Dicf::PART_ADJECTIVE },
    { "REVERSE",        Dicf::PART_ADJECTIVE },
    { "REVERSED",       Dicf::PART_ADJECTIVE },
    { "RETROFLEX",      Dicf::PART_ADJECTIVE },
    { "RIGHT",          Dicf::PART_ADJECTIVE },
    { "RIGHT-STEM",     Dicf::PART_ADJECTIVE },
    { "ROMANIAN",       Dicf::PART_ADJECTIVE },
    { "ROTATED",        Dicf::PART_ADJECTIVE },
    { "ROUNDED",        Dicf::PART_ADJECTIVE },
    { "ROUNDTOP",       Dicf::PART_ADJECTIVE },
    { "SARA",           Dicf::PART_ADJECTIVE }, // Used for Thai
    { "SCRIPT",         Dicf::PART_ADJECTIVE }, // “Khitan small script” OK
    { "SEMISOFT",       Dicf::PART_ADJECTIVE },
    { "SHARP",          Dicf::PART_ADJECTIVE },
    { "SHORT",          Dicf::PART_ADJECTIVE },
    /// @todo [decap] Arabic mark Sideways Noon gnunna — is it right?
    { "SIDEWAYS",       Dicf::PART_ADJECTIVE },
    { "SIGMOID",        Dicf::PART_ADJECTIVE },
    { "SIMPLIFIED",     Dicf::PART_ADJECTIVE },
    { "SLOAN",          Dicf::PART_ADJECTIVE },
    { "SMALL",          Dicf::PART_ADJECTIVE },
    { "SNAP",           Dicf::PART_ADJECTIVE }, // OK, music only
    { "SPACING",        Dicf::PART_ADJECTIVE },
    { "SPIDERY",        Dicf::PART_ADJECTIVE },
    { "SPLIT",          Dicf::PART_ADJECTIVE },
    { "SQUAT",          Dicf::PART_ADJECTIVE },
    { "SOFT",           Dicf::PART_ADJECTIVE },
    // Old SOUTH Arabian
    { "SOUTH",          Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT_ADJECTIVE  },
    { "SOUTHERN",       Dicf::PART_ADJECTIVE },
    { "SPRECHGESANG",   Dicf::PART_ADJECTIVE },
    { "STRAIGHT",       Dicf::PART_ADJECTIVE },
    { "STRETCHED",      Dicf::PART_ADJECTIVE },
    { "SUPERSCRIPT",    Dicf::PART_ADJECTIVE },
    { "SYLLABIC",       Dicf::PART_ADJECTIVE },
    { "TAILED",         Dicf::PART_ADJECTIVE },
    { "TAILLESS",       Dicf::PART_ADJECTIVE },
    { "TALL",           Dicf::PART_ADJECTIVE },
    { "THAM",           Dicf::PART_ADJECTIVE }, // not really correct, but let’s leave hora/tham lowcase
    { "THIRD-STAGE",    Dicf::PART_ADJECTIVE },
    { "THREE-D",        { Dicf::PART_ADJECTIVE, "three-D" } },
    { "THREE-LEGGED",   Dicf::PART_ADJECTIVE },
    { "TIGHT",          Dicf::PART_ADJECTIVE },
    { "TOP",            Dicf::PART_ADJECTIVE },
    { "TRIANGULAR",     Dicf::PART_ADJECTIVE },
    { "TRIPLE",         Dicf::PART_ADJECTIVE },
    { "TROKUTASTI",     Dicf::PART_ADJECTIVE },
    { "TRADITIONAL",    Dicf::PART_ADJECTIVE },
    { "TRUNCATED",      Dicf::PART_ADJECTIVE },
    { "TURNED",         Dicf::PART_ADJECTIVE },
    { "TWO-CIRCLE",     Dicf::PART_ADJECTIVE },
    { "UNBLENDED",      Dicf::PART_ADJECTIVE },
    { "UP",             Dicf::PART_ADJECTIVE },
    { "VERTICAL",       Dicf::PART_ADJECTIVE },
    { "VOCALIC",        Dicf::PART_ADJECTIVE },
    { "VOICED",         Dicf::PART_ADJECTIVE },
    { "VOICELESS",      Dicf::PART_ADJECTIVE },
    { "WESTERN",        Dicf::PART_ADJECTIVE },
    { "WIDE",           Dicf::PART_ADJECTIVE },

    // Starting with letter: sort by main word, then by letter
    { "N-ARY",          Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "L-SHAPED",       Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "S-SHAPED",       Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "U-SHAPED",       Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "H-TYPE",         Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "L-TYPE",         Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },

    // Sinhala
    { "ALPAPRAANA",     Dicf::PART_ADJECTIVE },
    { "AMBA",           Dicf::PART_ADJECTIVE },
    { "DANTAJA",        Dicf::PART_ADJECTIVE },
    { "DIGA",           Dicf::PART_ADJECTIVE },
    { "GAETTA-PILLA",   Dicf::PART_NOUN },
    { "GAYANUKITTA",    Dicf::PART_NOUN },
    { "KANTAJA",        Dicf::PART_ADJECTIVE },
    { "KETTI",          Dicf::PART_ADJECTIVE },
    { "KOMBUVA",        Dicf::PART_ADJECTIVE },
    { "LITH",           Dicf::PART_ADJECTIVE | Dicf::CAP_TITLE },
    { "MAHAAPRAANA",    Dicf::PART_ADJECTIVE },
    { "MUURDHAJA",      Dicf::PART_ADJECTIVE },
    { "SANYAKA",        Dicf::PART_ADJECTIVE },
    { "SANYOOGA",       Dicf::PART_ADJECTIVE },
    { "TAALUJA",        Dicf::PART_ADJECTIVE },

    // People’s names
    { "CELSIUS",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CLAUS",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "DAVID",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "EULER",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "FAHRENHEIT",     Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "FERRIS",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "FRANKS",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "FITZPATRICK",    Dicf::CAP_TITLE },
    { "HERMITIAN",      Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "MARY",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "MX",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PERNIN",         Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },   // Helen Pernin, author of shorthand
    { "PETRI",          Dicf::CAP_TITLE },
    { "PLANCK",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "TIRONIAN",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE | Dicf::TRIG_SCRIPT },
    { "WEIERSTRASS",    Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Myth/religion characters’ names
    { "AESCULAPIUS",    Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ALLAAH",         Dicf::CAP_TITLE },
    { "ALLAAHI",        Dicf::CAP_TITLE },
    { "ALLAAHU",        Dicf::CAP_TITLE },
    { "ALLAHOU",        Dicf::CAP_TITLE },
    { "HERMES",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HYGIEIA",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "JOVE",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SELENA",         Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Astronomy — 8 planets of Sol and Pluto
    { "JUPITER",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SATURN",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "URANUS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "NEPTUNE",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PLUTO",          Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Astronomy — zodiac
    { "ARIES",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "TAURUS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "GEMINI",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LEO",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "VIRGO",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LIBRA",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SCORPIUS",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SAGITTARIUS",    Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CAPRICORN",      Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "AQUARIUS",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PISCES",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "OPHIUCHUS",      Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Astronomy — rest
    { "ADMETOS",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "AMPHITRITE",     Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "APOLLON",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ASTRAEA",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "BELLONA",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CERES",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CHIRON",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CUPIDO",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "EGERIA",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ERIS",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "EUNOMIA",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "FORTUNA",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "GONGGONG",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HADES",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HAUMEA",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HEBE",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HYGIEA",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "IRENE",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "JUNO",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "KRONOS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LEUKOTHEA",      Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LILITH",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "MAKEMAKE",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "MELPOMENE",      Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "METIS",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "NESSUS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ORCUS",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PALLAS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PARTHENOPE",     Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PHOLUS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "POSEIDON",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PROSERPINA",     Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "PSYCHE",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "QUAOAR",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SEDNA",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "THETIS",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "TRANSPLUTO",     Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "VESTA",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "VICTORIA",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "VULCANUS",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ZEUS",           Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Other names
    { "ARTA",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "CHRISTMAS",      Dicf::CAP_TITLE },
    { "FARSI",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    // { "GARSHUNI",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE }, not really correct, but small is nicer
    { "HELLSCHREIBER",  Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HINDU",          Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "JAPAN",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "JERUSALEM",      Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "KAABA",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "KORANIC",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "LORRAINE",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ORTHODOX",       Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "RUMI",           Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },
    { "SHINTO",         Dicf::CAP_TITLE | Dicf::PART_MIXED },
    { "VOLAPUK",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },   // OK here
    { "YENISEI",        Dicf::CAP_TITLE | Dicf::PART_ADJECTIVE },   // OK here

    // Months
    { "JANUARY",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "FEBRUARY",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "MARCH",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "APRIL",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "MAY",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "JUNE",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "JULY",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "AUGUST",         Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SEPTEMBER",      Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "OCTOBER",        Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "NOVEMBER",       Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "DECEMBER",       Dicf::CAP_TITLE | Dicf::PART_NOUN },

    // Znamenny
    { "CHELYUSTKA",     Dicf::PART_NOUN },
    { "ZAPYATAYA",      Dicf::PART_NOUN },

    // Some letters
    { "A",              Dicf::PART_MAYBE_LETTER },
    { "-A",             Dicf::CAP_ALL },
    { "ALEF",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "AA",             Dicf::CAP_TITLE },
    { "AE",             Dicf::CAP_TITLE },
    { "AIN",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "AU",             Dicf::CAP_TITLE },
    { "BEH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "BET",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "B",              Dicf::CAP_TITLE },
    { "C",              Dicf::CAP_TITLE },
    { "D",              Dicf::CAP_TITLE },
    { "D-ETH",          { Dicf::PART_ADJECTIVE, "D-Eth" } },
    { "D-LEZH",         { Dicf::PART_ADJECTIVE, "D-Lezh" } },
    { "DAD",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "DAL",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "DALET",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "E",              Dicf::CAP_TITLE },
    { "EE",             Dicf::CAP_TITLE },
    { "EH",             Dicf::CAP_TITLE },
    { "ESH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "EU",             Dicf::CAP_TITLE },
    { "F",              Dicf::CAP_TITLE },
    { "FEH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "G",              Dicf::CAP_TITLE },
    { "GHAIN",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "GIMEL",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "H",              Dicf::CAP_TITLE },
    { "HAH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HE",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "HEH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "I",              Dicf::PART_MAYBE_LETTER },  // Because of Znamenny
    { "J",              Dicf::CAP_TITLE },
    { "JEEM",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "K",              Dicf::CAP_TITLE },
    { "KAF",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "KHAH",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "L",              Dicf::CAP_TITLE },
    { "LLA",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LAM",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "LAMED",          Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "M",              Dicf::CAP_TITLE },
    { "MEEM",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "N",              Dicf::CAP_TITLE },
    { "NOON",           Dicf::CAP_TITLE | Dicf::PART_NOUN },    // OK here, no English noon (12:00)
    //{ "NI",             Dicf::CAP_TITLE },    // widely used in cuneiform, IDK what to do
    { "O",              Dicf::CAP_TITLE },
    { "OE",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "OM",             Dicf::CAP_TITLE },
    { "OU",             Dicf::CAP_TITLE },
    { "OPEN-O",         { Dicf::PART_NOUN, "open-O" } },
    { "P",              Dicf::CAP_TITLE },
    { "Q",              Dicf::CAP_TITLE },
    { "QAF",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "R",              Dicf::CAP_TITLE },
    { "REH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "RESH",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "REVERSED-SCHWA", { Dicf::PART_NOUN, "reversed-Schwa" } },
    { "RISH",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "S",              Dicf::PART_MAYBE_LETTER },  // Because of Znamenny
    { "SA",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SAD",            Dicf::PART_MAYBE_LETTER },
    { "SEEN",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "SHEEN",          Dicf::PART_MAYBE_LETTER },
    { "T",              Dicf::CAP_TITLE },
    { "T-THETA",        { Dicf::PART_ADJECTIVE, "T-Theta" } },
    { "TAH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "TEH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "THAL",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "THEH",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "TH",             Dicf::CAP_TITLE },
    { "U",              Dicf::CAP_TITLE },
    { "UE",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "V",              Dicf::CAP_TITLE },
    { "VAV",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "W",              Dicf::CAP_TITLE },
    { "WAW",            Dicf::CAP_TITLE },
    { "X",              Dicf::CAP_TITLE },
    { "Y",              Dicf::CAP_TITLE },
    { "YER",            Dicf::CAP_TITLE | Dicf::IF_SCRIPT | Dicf::PART_NOUN },
    { "YU",             Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "YEH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "Z",              Dicf::CAP_TITLE },
    { "ZAH",            Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "ZAIN",           Dicf::CAP_TITLE | Dicf::PART_NOUN },
    { "J-SIMPLIFIED",   Dicf::CAP_TITLE },
    { "WAW-AYIN-RESH",  { Dicf::PART_NOUN, "Waw-Ayin-Resh" } },
    { "RESH-AYIN-DALETH", { Dicf::PART_NOUN, "Resh-Ayin-Daleth" } },
    { "AYIN-DALETH",    { Dicf::PART_NOUN, "Ayin-Daleth" } },
    { "RESH-AYIN",      { Dicf::PART_NOUN, "Resh-Ayin" } },
    { "ZAYIN-YODH",     { Dicf::PART_NOUN, "Zayin-Yodh" } },
    { "GIMEL-HETH",     { Dicf::PART_NOUN, "Gimel-Heth" } },
    { "MEM-QOPH",       { Dicf::PART_NOUN, "Mem-Qoph" } },
    { "DALETH-RESH",    { Dicf::PART_NOUN, "Daleth-Resh" } },

    // Byzantine notes
    //{ "PA",             Dicf::CAP_TITLE }, intersects
    { "NANA",           Dicf::CAP_TITLE },
    { "DI",             Dicf::CAP_TITLE },
    { "KE",             Dicf::CAP_TITLE },
    { "ZO",             Dicf::CAP_TITLE },
    { "VOU",            Dicf::CAP_TITLE },
    { "NI",             Dicf::CAP_TITLE },

    // Some prepositions
    { "WITH",           Dicf::CAP_SMALL },
    //{ "AND",            Dicf::CAP_SMALL },    // Tricky word, all And’s are tested manually
    { "JOINER",         Dicf::CAP_SMALL },
    //{ "ABOVE",          Dicf::CAP_SMALL },    // Tricky word, all above’s are tested manually
    { "FOR",            Dicf::CAP_SMALL },
};
