#pragma once

#define UCD_PVA "PropertyValueAliases.txt"
#define UCD_NAMES "NamesList.txt"
#define UCD_ALIASES "NameAliases.txt"
#define UCD_SCRIPTS "Scripts.txt"
#define UCD_UDATA "UnicodeData.txt"
#define UCD_PROP "PropList.txt"
#define UCD_BLOCKS "Blocks.txt"
#define UCD_MAIN "UnicodeData.txt"
#define DER_AGE "DerivedAge.txt"
#define DER_CORE "DerivedCoreProperties.txt"
#define DER_NAME "DerivedName.txt"
#define HAN_DIC "Unihan_DictionaryLikeData.txt"
#define HAN_NUM_VALUE "Unihan_NumericValues.txt"
#define HAN_IRG "Unihan_IRGSources.txt"
#define EMOJI_TEST "emoji-test.txt"
#define ENTITIES_HTML "entities.htm"
#define ENTITIES_JSON "entities.json"
#define LIBRARY_XML "library.xml"
#define MISCFILES "MiscFiles/"
#define RAWDATA "MiscFiles/RawData/"
#define EGYP_UNICODE "signunicode.xml"
#define EGYP_DESCRIPTION "signdescriptioneng.xml"
#define SUTTON_TXT "signwritingsequences.txt"

#define MAPPINGS "MiscFiles/Mappings/"
#define OLD_APPLE2_1 "APL2ALT1.TXT"
#define OLD_APPLE2_2 "APL2ALT2.TXT"
#define OLD_APPLE2_3 "APL2ICHG.TXT"
#define OLD_APPLE2_4 "APL2PRIM.TXT"

void checkLoader();
