// Automatically generated, do not edit!

#include "UcAutoDefines.h"

using OC = uc::OldComp;

constinit const Flags<uc::OldComp> oldCompRange_0[] {
OC::TELETEXT | OC::TANDY_TRS80,  // 2c6
OC::TELETEXT,  // 2c7
OC::NONE,  // 2c8
OC::TELETEXT,  // 2c9
OC::TELETEXT | OC::TANDY_TRS80,  // 2ca
OC::TELETEXT | OC::TANDY_TRS80,  // 2cb
OC::TELETEXT,  // 2cc
OC::NONE,  // 2cd
OC::NONE,  // 2ce
OC::NONE,  // 2cf
OC::NONE,  // 2d0
OC::NONE,  // 2d1
OC::NONE,  // 2d2
OC::NONE,  // 2d3
OC::NONE,  // 2d4
OC::NONE,  // 2d5
OC::NONE,  // 2d6
OC::NONE,  // 2d7
OC::TELETEXT,  // 2d8
OC::RISC_OS | OC::TELETEXT,  // 2d9
OC::TELETEXT | OC::TANDY_TRS80,  // 2da
OC::TELETEXT,  // 2db
OC::TELETEXT | OC::TANDY_TRS80,  // 2dc
OC::TELETEXT,  // 2dd
};
static_assert(std::size(oldCompRange_0) == 24, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_1[] {
OC::RISC_OS,  // 2013
OC::RISC_OS,  // 2014
OC::NONE,  // 2015
OC::RISC_OS | OC::TELETEXT,  // 2016
OC::NONE,  // 2017
OC::AMSTRAD_CPC | OC::MSX | OC::RISC_OS | OC::TELETEXT,  // 2018
OC::AMSTRAD_CPC | OC::MSX | OC::RISC_OS | OC::TELETEXT,  // 2019
OC::NONE,  // 201a
OC::TANDY_TRS80,  // 201b
OC::MSX | OC::RISC_OS | OC::TELETEXT,  // 201c
OC::MSX | OC::RISC_OS | OC::TELETEXT,  // 201d
OC::RISC_OS,  // 201e
OC::NONE,  // 201f
OC::ATARI_ST | OC::RISC_OS | OC::TANDY_TRS80 | OC::HP_TERMINAL,  // 2020
OC::MSX | OC::RISC_OS,  // 2021
OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON,  // 2022
OC::NONE,  // 2023
OC::NONE,  // 2024
OC::NONE,  // 2025
OC::APPLE | OC::RISC_OS,  // 2026
OC::NONE,  // 2027
OC::NONE,  // 2028
OC::NONE,  // 2029
OC::NONE,  // 202a
OC::NONE,  // 202b
OC::NONE,  // 202c
OC::NONE,  // 202d
OC::NONE,  // 202e
OC::NONE,  // 202f
OC::MSX | OC::RISC_OS | OC::TELETEXT,  // 2030
OC::NONE,  // 2031
OC::NONE,  // 2032
OC::NONE,  // 2033
OC::NONE,  // 2034
OC::NONE,  // 2035
OC::NONE,  // 2036
OC::NONE,  // 2037
OC::NONE,  // 2038
OC::RISC_OS,  // 2039
OC::RISC_OS,  // 203a
OC::NONE,  // 203b
OC::KORVET,  // 203c
OC::NONE,  // 203d
OC::NONE,  // 203e
OC::NONE,  // 203f
OC::NONE,  // 2040
OC::NONE,  // 2041
OC::NONE,  // 2042
OC::NONE,  // 2043
OC::RISC_OS,  // 2044
};
static_assert(std::size(oldCompRange_1) == 50, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_2[] {
OC::HP_TERMINAL,  // 2070
OC::NONE,  // 2071
OC::NONE,  // 2072
OC::NONE,  // 2073
OC::RISC_OS | OC::HP_TERMINAL,  // 2074
OC::HP_TERMINAL,  // 2075
OC::HP_TERMINAL,  // 2076
OC::HP_TERMINAL,  // 2077
OC::HP_TERMINAL,  // 2078
OC::HP_TERMINAL,  // 2079
OC::NONE,  // 207a
OC::NONE,  // 207b
OC::NONE,  // 207c
OC::NONE,  // 207d
OC::NONE,  // 207e
OC::ATARI_ST | OC::MSX,  // 207f
};
static_assert(std::size(oldCompRange_2) == 16, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_3[] {
OC::TELETEXT,  // 20a0
OC::NONE,  // 20a1
OC::MSX,  // 20a2
OC::NONE,  // 20a3
OC::NONE,  // 20a4
OC::NONE,  // 20a5
OC::NONE,  // 20a6
OC::MSX,  // 20a7
OC::NONE,  // 20a8
OC::MSX,  // 20a9
OC::NONE,  // 20aa
OC::NONE,  // 20ab
OC::RISC_OS,  // 20ac
};
static_assert(std::size(oldCompRange_3) == 13, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_4[] {
OC::TANDY_TRS80,  // 2105
};
static_assert(std::size(oldCompRange_4) == 1, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_5[] {
OC::TANDY_TRS80,  // 211e
OC::NONE,  // 211f
OC::NONE,  // 2120
OC::NONE,  // 2121
OC::ATARI_ST | OC::RISC_OS | OC::TELETEXT | OC::TANDY_TRS80 | OC::SHARP_MZ,  // 2122
};
static_assert(std::size(oldCompRange_5) == 5, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_6[] {
OC::SHARP_MZ,  // 2153
OC::SHARP_MZ,  // 2154
OC::NONE,  // 2155
OC::NONE,  // 2156
OC::NONE,  // 2157
OC::NONE,  // 2158
OC::NONE,  // 2159
OC::NONE,  // 215a
OC::TELETEXT,  // 215b
OC::TELETEXT,  // 215c
OC::TELETEXT,  // 215d
OC::TELETEXT,  // 215e
};
static_assert(std::size(oldCompRange_6) == 12, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_7[] {
OC::AMSTRAD_CPC | OC::APPLE | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::SHARP_MZ | OC::HP_TERMINAL,  // 2190
OC::AMSTRAD_CPC | OC::APPLE | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::ORIC | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2191
OC::AMSTRAD_CPC | OC::APPLE | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::RISC_OS | OC::TELETEXT | OC::TANDY_TRS80 | OC::KORVET | OC::SHARP_MZ | OC::HP_TERMINAL | OC::KAYPRO,  // 2192
OC::AMSTRAD_CPC | OC::APPLE | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::RISC_OS | OC::TELETEXT | OC::TANDY_TRS80 | OC::KORVET | OC::SHARP_MZ | OC::HP_TERMINAL | OC::KAYPRO,  // 2193
OC::SHARP_MZ,  // 2194
OC::KORVET | OC::SHARP_MZ,  // 2195
OC::AQUARIUS | OC::SHARP_MZ,  // 2196
OC::AQUARIUS | OC::SHARP_MZ,  // 2197
OC::AQUARIUS | OC::SHARP_MZ,  // 2198
OC::AQUARIUS | OC::SHARP_MZ,  // 2199
OC::NONE,  // 219a
OC::NONE,  // 219b
OC::NONE,  // 219c
OC::NONE,  // 219d
OC::NONE,  // 219e
OC::NONE,  // 219f
OC::NONE,  // 21a0
OC::AMSTRAD_CPC,  // 21a1
OC::NONE,  // 21a2
OC::NONE,  // 21a3
OC::OHIO_SCIENTIFIC,  // 21a4
OC::OHIO_SCIENTIFIC,  // 21a5
OC::OHIO_SCIENTIFIC,  // 21a6
OC::OHIO_SCIENTIFIC,  // 21a7
OC::KORVET,  // 21a8
OC::NONE,  // 21a9
OC::NONE,  // 21aa
OC::NONE,  // 21ab
OC::NONE,  // 21ac
OC::NONE,  // 21ad
OC::NONE,  // 21ae
OC::NONE,  // 21af
OC::NONE,  // 21b0
OC::NONE,  // 21b1
OC::AMSTRAD_CPC | OC::APPLE,  // 21b2
};
static_assert(std::size(oldCompRange_7) == 35, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_8[] {
OC::OHIO_SCIENTIFIC,  // 21d0
OC::NONE,  // 21d1
OC::OHIO_SCIENTIFIC,  // 21d2
OC::NONE,  // 21d3
OC::OHIO_SCIENTIFIC,  // 21d4
};
static_assert(std::size(oldCompRange_8) == 5, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_9[] {
OC::ATARI_ST | OC::RISC_OS,  // 21e6
OC::ATARI_ST | OC::RISC_OS,  // 21e7
OC::ATARI_ST | OC::RISC_OS,  // 21e8
OC::ATARI_ST | OC::RISC_OS,  // 21e9
};
static_assert(std::size(oldCompRange_9) == 4, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_10[] {
OC::RISC_OS | OC::HP_TERMINAL,  // 2202
OC::NONE,  // 2203
OC::NONE,  // 2204
OC::MSX,  // 2205
OC::TANDY_TRS80 | OC::OHIO_SCIENTIFIC,  // 2206
OC::RISC_OS | OC::HP_TERMINAL,  // 2207
OC::ATARI_ST | OC::MSX,  // 2208
OC::NONE,  // 2209
OC::NONE,  // 220a
OC::NONE,  // 220b
OC::NONE,  // 220c
OC::NONE,  // 220d
OC::NONE,  // 220e
OC::NONE,  // 220f
OC::NONE,  // 2210
OC::TANDY_TRS80,  // 2211
OC::RISC_OS,  // 2212
OC::RISC_OS,  // 2213
OC::NONE,  // 2214
OC::NONE,  // 2215
OC::NONE,  // 2216
OC::NONE,  // 2217
OC::NONE,  // 2218
OC::ATARI_ST | OC::MSX,  // 2219
OC::ATARI_ST | OC::MSX | OC::RISC_OS | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 221a
OC::NONE,  // 221b
OC::NONE,  // 221c
OC::SHARP_MZ | OC::HP_TERMINAL,  // 221d
OC::ATARI_ST | OC::MSX | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::HP_TERMINAL,  // 221e
OC::NONE,  // 221f
OC::NONE,  // 2220
OC::NONE,  // 2221
OC::NONE,  // 2222
OC::NONE,  // 2223
OC::NONE,  // 2224
OC::NONE,  // 2225
OC::NONE,  // 2226
OC::ATARI_ST,  // 2227
OC::NONE,  // 2228
OC::ATARI_ST | OC::MSX | OC::RISC_OS,  // 2229
OC::RISC_OS,  // 222a
OC::OHIO_SCIENTIFIC,  // 222b
OC::NONE,  // 222c
OC::NONE,  // 222d
OC::ATARI_ST,  // 222e
OC::NONE,  // 222f
OC::NONE,  // 2230
OC::NONE,  // 2231
OC::NONE,  // 2232
OC::NONE,  // 2233
OC::NONE,  // 2234
OC::NONE,  // 2235
OC::NONE,  // 2236
OC::NONE,  // 2237
OC::NONE,  // 2238
OC::NONE,  // 2239
OC::NONE,  // 223a
OC::NONE,  // 223b
OC::OHIO_SCIENTIFIC,  // 223c
OC::MSX,  // 223d
OC::NONE,  // 223e
OC::NONE,  // 223f
OC::NONE,  // 2240
OC::NONE,  // 2241
OC::NONE,  // 2242
OC::RISC_OS | OC::HP_TERMINAL,  // 2243
OC::NONE,  // 2244
OC::MSX,  // 2245
OC::NONE,  // 2246
OC::NONE,  // 2247
OC::ATARI_ST | OC::MSX | OC::TANDY_TRS80 | OC::OHIO_SCIENTIFIC,  // 2248
};
static_assert(std::size(oldCompRange_10) == 71, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_11[] {
OC::RISC_OS | OC::TANDY_TRS80 | OC::SHARP_MZ,  // 2260
OC::ATARI_ST | OC::MSX | OC::RISC_OS | OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2261
OC::NONE,  // 2262
OC::NONE,  // 2263
OC::ATARI_ST | OC::MSX | OC::RISC_OS | OC::TANDY_TRS80 | OC::SHARP_MZ,  // 2264
OC::ATARI_ST | OC::MSX | OC::RISC_OS | OC::TANDY_TRS80 | OC::SHARP_MZ,  // 2265
};
static_assert(std::size(oldCompRange_11) == 6, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_12[] {
OC::SHARP_MZ,  // 2295
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 2296
OC::AMSTRAD_CPC,  // 2297
OC::NONE,  // 2298
OC::AMSTRAD_CPC,  // 2299
OC::NONE,  // 229a
OC::NONE,  // 229b
OC::NONE,  // 229c
OC::NONE,  // 229d
OC::SHARP_MZ,  // 229e
OC::AMSTRAD_CPC,  // 229f
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 22a0
OC::NONE,  // 22a1
OC::NONE,  // 22a2
OC::AMSTRAD_CPC,  // 22a3
};
static_assert(std::size(oldCompRange_12) == 15, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_13[] {
OC::AMSTRAD_CPC | OC::TANDY_TRS80,  // 2301
OC::ATARI_ST | OC::MSX | OC::KORVET,  // 2302
OC::NONE,  // 2303
OC::NONE,  // 2304
OC::NONE,  // 2305
OC::NONE,  // 2306
OC::TANDY_TRS80,  // 2307
OC::NONE,  // 2308
OC::NONE,  // 2309
OC::NONE,  // 230a
OC::NONE,  // 230b
OC::NONE,  // 230c
OC::NONE,  // 230d
OC::NONE,  // 230e
OC::NONE,  // 230f
OC::ATARI_ST | OC::MSX,  // 2310
OC::NONE,  // 2311
OC::NONE,  // 2312
OC::NONE,  // 2313
OC::NONE,  // 2314
OC::NONE,  // 2315
OC::NONE,  // 2316
OC::NONE,  // 2317
OC::NONE,  // 2318
OC::NONE,  // 2319
OC::NONE,  // 231a
OC::AMSTRAD_CPC | OC::APPLE,  // 231b
OC::NONE,  // 231c
OC::NONE,  // 231d
OC::NONE,  // 231e
OC::NONE,  // 231f
OC::ATARI_ST | OC::MSX | OC::SHARP_MZ | OC::HP_TERMINAL,  // 2320
OC::ATARI_ST | OC::MSX | OC::SHARP_MZ | OC::HP_TERMINAL,  // 2321
};
static_assert(std::size(oldCompRange_13) == 33, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_14[] {
OC::AMSTRAD_CPC,  // 237b
OC::NONE,  // 237c
OC::NONE,  // 237d
OC::AMSTRAD_CPC | OC::TANDY_TRS80,  // 237e
OC::AMSTRAD_CPC,  // 237f
OC::NONE,  // 2380
OC::NONE,  // 2381
OC::NONE,  // 2382
OC::NONE,  // 2383
OC::NONE,  // 2384
OC::NONE,  // 2385
OC::NONE,  // 2386
OC::NONE,  // 2387
OC::NONE,  // 2388
OC::NONE,  // 2389
OC::NONE,  // 238a
OC::NONE,  // 238b
OC::NONE,  // 238c
OC::AMSTRAD_CPC,  // 238d
};
static_assert(std::size(oldCompRange_14) == 19, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_15[] {
OC::HP_TERMINAL,  // 23ae
OC::NONE,  // 23af
OC::NONE,  // 23b0
OC::NONE,  // 23b1
OC::NONE,  // 23b2
OC::NONE,  // 23b3
OC::NONE,  // 23b4
OC::NONE,  // 23b5
OC::NONE,  // 23b6
OC::NONE,  // 23b7
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::MINITEL | OC::KAYPRO,  // 23b8
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::MINITEL | OC::KAYPRO,  // 23b9
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::MINITEL | OC::KAYPRO,  // 23ba
OC::NONE,  // 23bb
OC::NONE,  // 23bc
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::MINITEL | OC::KAYPRO,  // 23bd
OC::AMSTRAD_CPC,  // 23be
OC::NONE,  // 23bf
OC::NONE,  // 23c0
OC::NONE,  // 23c1
OC::NONE,  // 23c2
OC::NONE,  // 23c3
OC::NONE,  // 23c4
OC::NONE,  // 23c5
OC::NONE,  // 23c6
OC::NONE,  // 23c7
OC::NONE,  // 23c8
OC::NONE,  // 23c9
OC::AMSTRAD_CPC,  // 23ca
OC::NONE,  // 23cb
OC::AMSTRAD_CPC,  // 23cc
};
static_assert(std::size(oldCompRange_15) == 31, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_16[] {
OC::SHARP_MZ,  // 23e9
OC::SHARP_MZ,  // 23ea
OC::SHARP_MZ,  // 23eb
OC::SHARP_MZ,  // 23ec
};
static_assert(std::size(oldCompRange_16) == 4, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_17[] {
OC::HP_TERMINAL,  // 2400
OC::HP_TERMINAL,  // 2401
OC::HP_TERMINAL,  // 2402
OC::HP_TERMINAL,  // 2403
OC::HP_TERMINAL,  // 2404
OC::HP_TERMINAL,  // 2405
OC::HP_TERMINAL,  // 2406
OC::HP_TERMINAL,  // 2407
OC::HP_TERMINAL,  // 2408
OC::HP_TERMINAL,  // 2409
OC::HP_TERMINAL,  // 240a
OC::HP_TERMINAL,  // 240b
OC::ATARI_ST | OC::HP_TERMINAL,  // 240c
OC::ATARI_ST | OC::TANDY_TRS80 | OC::HP_TERMINAL,  // 240d
OC::HP_TERMINAL,  // 240e
OC::HP_TERMINAL,  // 240f
OC::HP_TERMINAL,  // 2410
OC::HP_TERMINAL,  // 2411
OC::HP_TERMINAL,  // 2412
OC::HP_TERMINAL,  // 2413
OC::HP_TERMINAL,  // 2414
OC::HP_TERMINAL,  // 2415
OC::HP_TERMINAL,  // 2416
OC::HP_TERMINAL,  // 2417
OC::HP_TERMINAL,  // 2418
OC::HP_TERMINAL,  // 2419
OC::HP_TERMINAL,  // 241a
OC::ATARI_ST | OC::ATARI_8BIT | OC::HP_TERMINAL,  // 241b
OC::HP_TERMINAL,  // 241c
OC::HP_TERMINAL,  // 241d
OC::HP_TERMINAL,  // 241e
OC::HP_TERMINAL,  // 241f
OC::NONE,  // 2420
OC::NONE,  // 2421
OC::NONE,  // 2422
OC::NONE,  // 2423
OC::NONE,  // 2424
OC::APPLE,  // 2425
OC::AMSTRAD_CPC,  // 2426
OC::SHARP_MZ,  // 2427
OC::TANDY_TRS80 | OC::SHARP_MZ | OC::HP_TERMINAL,  // 2428
OC::AMSTRAD_CPC,  // 2429
};
static_assert(std::size(oldCompRange_17) == 42, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_18[] {
OC::AMSTRAD_CPC | OC::APPLE | OC::ATARI_8BIT | OC::MINITEL | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::ROBOTRON | OC::HP_TERMINAL,  // 2500
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2501
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MINITEL | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2502
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2503
OC::NONE,  // 2504
OC::NONE,  // 2505
OC::NONE,  // 2506
OC::NONE,  // 2507
OC::NONE,  // 2508
OC::NONE,  // 2509
OC::NONE,  // 250a
OC::NONE,  // 250b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 250c
OC::NONE,  // 250d
OC::NONE,  // 250e
OC::HP_TERMINAL,  // 250f
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2510
OC::NONE,  // 2511
OC::NONE,  // 2512
OC::HP_TERMINAL,  // 2513
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2514
OC::NONE,  // 2515
OC::NONE,  // 2516
OC::HP_TERMINAL,  // 2517
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2518
OC::NONE,  // 2519
OC::NONE,  // 251a
OC::HP_TERMINAL,  // 251b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 251c
OC::TELETEXT,  // 251d
OC::NONE,  // 251e
OC::NONE,  // 251f
OC::HP_TERMINAL,  // 2520
OC::NONE,  // 2521
OC::NONE,  // 2522
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2523
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2524
OC::TELETEXT,  // 2525
OC::NONE,  // 2526
OC::NONE,  // 2527
OC::HP_TERMINAL,  // 2528
OC::NONE,  // 2529
OC::NONE,  // 252a
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 252b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 252c
OC::NONE,  // 252d
OC::NONE,  // 252e
OC::TELETEXT | OC::HP_TERMINAL,  // 252f
OC::NONE,  // 2530
OC::NONE,  // 2531
OC::NONE,  // 2532
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 2533
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2534
OC::NONE,  // 2535
OC::NONE,  // 2536
OC::TELETEXT | OC::HP_TERMINAL,  // 2537
OC::NONE,  // 2538
OC::NONE,  // 2539
OC::NONE,  // 253a
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 253b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::RISC_OS | OC::TELETEXT | OC::SHARP_MZ | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 253c
OC::NONE,  // 253d
OC::NONE,  // 253e
OC::TELETEXT | OC::HP_TERMINAL,  // 253f
OC::NONE,  // 2540
OC::NONE,  // 2541
OC::HP_TERMINAL,  // 2542
OC::NONE,  // 2543
OC::NONE,  // 2544
OC::NONE,  // 2545
OC::NONE,  // 2546
OC::HP_TERMINAL,  // 2547
OC::HP_TERMINAL,  // 2548
OC::HP_TERMINAL,  // 2549
OC::HP_TERMINAL,  // 254a
OC::OHIO_SCIENTIFIC | OC::HP_TERMINAL,  // 254b
OC::NONE,  // 254c
OC::NONE,  // 254d
OC::NONE,  // 254e
OC::NONE,  // 254f
OC::HP_TERMINAL,  // 2550
OC::HP_TERMINAL,  // 2551
OC::NONE,  // 2552
OC::NONE,  // 2553
OC::NONE,  // 2554
OC::NONE,  // 2555
OC::NONE,  // 2556
OC::NONE,  // 2557
OC::NONE,  // 2558
OC::NONE,  // 2559
OC::NONE,  // 255a
OC::NONE,  // 255b
OC::NONE,  // 255c
OC::NONE,  // 255d
OC::HP_TERMINAL,  // 255e
OC::HP_TERMINAL,  // 255f
OC::NONE,  // 2560
OC::HP_TERMINAL,  // 2561
OC::HP_TERMINAL,  // 2562
OC::NONE,  // 2563
OC::HP_TERMINAL,  // 2564
OC::HP_TERMINAL,  // 2565
OC::NONE,  // 2566
OC::HP_TERMINAL,  // 2567
OC::HP_TERMINAL,  // 2568
OC::NONE,  // 2569
OC::HP_TERMINAL,  // 256a
OC::HP_TERMINAL,  // 256b
OC::HP_TERMINAL,  // 256c
OC::COMMODORE | OC::RISC_OS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 256d
OC::COMMODORE | OC::RISC_OS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 256e
OC::COMMODORE | OC::RISC_OS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 256f
OC::COMMODORE | OC::RISC_OS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2570
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2571
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2572
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2573
OC::AMSTRAD_CPC | OC::RISC_OS,  // 2574
OC::AMSTRAD_CPC | OC::RISC_OS,  // 2575
OC::AMSTRAD_CPC | OC::RISC_OS,  // 2576
OC::AMSTRAD_CPC | OC::RISC_OS,  // 2577
OC::NONE,  // 2578
OC::NONE,  // 2579
OC::NONE,  // 257a
OC::NONE,  // 257b
OC::NONE,  // 257c
OC::NONE,  // 257d
OC::NONE,  // 257e
OC::NONE,  // 257f
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2580
OC::AQUARIUS | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2581
OC::AQUARIUS | OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2582
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2583
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2584
OC::COMMODORE | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2585
OC::AQUARIUS | OC::MSX | OC::COMMODORE | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2586
OC::AQUARIUS | OC::COMMODORE | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2587
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MINITEL | OC::MSX | OC::ORIC | OC::COMMODORE | OC::RISC_OS | OC::SINCLAIR | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2588
OC::APPLE | OC::AQUARIUS | OC::COMMODORE,  // 2589
OC::AQUARIUS | OC::MSX | OC::COMMODORE,  // 258a
OC::COMMODORE,  // 258b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::MSX | OC::ORIC | OC::COMMODORE | OC::SINCLAIR | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 258c
OC::AQUARIUS | OC::COMMODORE | OC::OHIO_SCIENTIFIC,  // 258d
OC::AQUARIUS | OC::MSX | OC::COMMODORE | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 258e
OC::APPLE | OC::AQUARIUS | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 258f
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MINITEL | OC::MSX | OC::ORIC | OC::COMMODORE | OC::SINCLAIR | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 2590
OC::NONE,  // 2591
OC::AMSTRAD_CPC | OC::APPLE | OC::AQUARIUS | OC::ORIC | OC::COMMODORE | OC::RISC_OS | OC::SINCLAIR | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 2592
OC::NONE,  // 2593
OC::APPLE | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2594
OC::APPLE | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2595
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2596
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2597
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 2598
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::ROBOTRON | OC::KAYPRO,  // 2599
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 259a
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::ROBOTRON | OC::KAYPRO,  // 259b
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::ROBOTRON | OC::KAYPRO,  // 259c
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::HP_TERMINAL | OC::KAYPRO,  // 259d
OC::AMSTRAD_CPC | OC::MSX | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 259e
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::SINCLAIR | OC::TANDY_COCO | OC::ROBOTRON | OC::KAYPRO,  // 259f
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MSX | OC::TELETEXT | OC::SHARP_MZ,  // 25a0
OC::AMSTRAD_CPC,  // 25a1
OC::NONE,  // 25a2
OC::NONE,  // 25a3
OC::NONE,  // 25a4
OC::NONE,  // 25a5
OC::NONE,  // 25a6
OC::NONE,  // 25a7
OC::NONE,  // 25a8
OC::NONE,  // 25a9
OC::AQUARIUS,  // 25aa
OC::NONE,  // 25ab
OC::MSX | OC::KORVET,  // 25ac
OC::TANDY_TRS80,  // 25ad
OC::NONE,  // 25ae
OC::OHIO_SCIENTIFIC,  // 25af
OC::NONE,  // 25b0
OC::NONE,  // 25b1
OC::AMSTRAD_CPC | OC::AQUARIUS,  // 25b2
OC::NONE,  // 25b3
OC::NONE,  // 25b4
OC::NONE,  // 25b5
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::KORVET | OC::OHIO_SCIENTIFIC,  // 25b6
OC::NONE,  // 25b7
OC::NONE,  // 25b8
OC::NONE,  // 25b9
OC::NONE,  // 25ba
OC::NONE,  // 25bb
OC::AMSTRAD_CPC | OC::AQUARIUS,  // 25bc
OC::NONE,  // 25bd
OC::NONE,  // 25be
OC::NONE,  // 25bf
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::KORVET | OC::OHIO_SCIENTIFIC,  // 25c0
OC::NONE,  // 25c1
OC::NONE,  // 25c2
OC::NONE,  // 25c3
OC::NONE,  // 25c4
OC::NONE,  // 25c5
OC::APPLE,  // 25c6
OC::MSX | OC::ROBOTRON,  // 25c7
OC::NONE,  // 25c8
OC::NONE,  // 25c9
OC::NONE,  // 25ca
OC::AMSTRAD_CPC | OC::MSX | OC::COMMODORE | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 25cb
OC::NONE,  // 25cc
OC::NONE,  // 25cd
OC::NONE,  // 25ce
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::MSX | OC::TELETEXT,  // 25cf
OC::NONE,  // 25d0
OC::NONE,  // 25d1
OC::NONE,  // 25d2
OC::NONE,  // 25d3
OC::NONE,  // 25d4
OC::NONE,  // 25d5
OC::NONE,  // 25d6
OC::NONE,  // 25d7
OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::KORVET | OC::SHARP_MZ | OC::ROBOTRON,  // 25d8
OC::MSX | OC::COMMODORE,  // 25d9
OC::NONE,  // 25da
OC::NONE,  // 25db
OC::NONE,  // 25dc
OC::NONE,  // 25dd
OC::NONE,  // 25de
OC::NONE,  // 25df
OC::NONE,  // 25e0
OC::NONE,  // 25e1
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::COMMODORE | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 25e2
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::COMMODORE | OC::TELETEXT | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 25e3
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 25e4
OC::AMSTRAD_CPC | OC::ATARI_8BIT | OC::COMMODORE | OC::TELETEXT | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 25e5
OC::SHARP_MZ,  // 25e6
OC::NONE,  // 25e7
OC::NONE,  // 25e8
OC::NONE,  // 25e9
OC::NONE,  // 25ea
OC::NONE,  // 25eb
OC::NONE,  // 25ec
OC::NONE,  // 25ed
OC::NONE,  // 25ee
OC::NONE,  // 25ef
OC::AMSTRAD_CPC | OC::RISC_OS,  // 25f0
OC::AMSTRAD_CPC,  // 25f1
OC::AMSTRAD_CPC,  // 25f2
OC::AMSTRAD_CPC,  // 25f3
OC::AMSTRAD_CPC,  // 25f4
OC::AMSTRAD_CPC,  // 25f5
OC::AMSTRAD_CPC,  // 25f6
OC::AMSTRAD_CPC,  // 25f7
OC::NONE,  // 25f8
OC::NONE,  // 25f9
OC::NONE,  // 25fa
OC::NONE,  // 25fb
OC::SHARP_MZ,  // 25fc
OC::NONE,  // 25fd
OC::SHARP_MZ,  // 25fe
OC::NONE,  // 25ff
OC::SHARP_MZ,  // 2600
OC::NONE,  // 2601
OC::SHARP_MZ,  // 2602
};
static_assert(std::size(oldCompRange_18) == 259, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_19[] {
OC::AMSTRAD_CPC | OC::TANDY_TRS80,  // 2639
OC::AMSTRAD_CPC | OC::MSX | OC::TANDY_TRS80 | OC::KORVET,  // 263a
OC::MSX | OC::KORVET,  // 263b
OC::AMSTRAD_CPC | OC::MSX | OC::KORVET | OC::SHARP_MZ,  // 263c
OC::NONE,  // 263d
OC::NONE,  // 263e
OC::NONE,  // 263f
OC::AMSTRAD_CPC | OC::MSX | OC::TANDY_TRS80,  // 2640
OC::NONE,  // 2641
OC::AMSTRAD_CPC | OC::MSX | OC::TANDY_TRS80,  // 2642
};
static_assert(std::size(oldCompRange_19) == 10, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_20[] {
OC::ROBOTRON,  // 265f
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2660
OC::NONE,  // 2661
OC::NONE,  // 2662
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2663
OC::NONE,  // 2664
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2665
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::ATARI_8BIT | OC::MSX | OC::COMMODORE | OC::TANDY_TRS80 | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 2666
OC::NONE,  // 2667
OC::NONE,  // 2668
OC::AMSTRAD_CPC,  // 2669
OC::AMSTRAD_CPC | OC::ATARI_ST | OC::MSX | OC::TELETEXT,  // 266a
OC::MSX,  // 266b
OC::KORVET,  // 266c
};
static_assert(std::size(oldCompRange_20) == 14, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_21[] {
OC::SHARP_MZ,  // 26aa
OC::NONE,  // 26ab
OC::SHARP_MZ,  // 26ac
};
static_assert(std::size(oldCompRange_21) == 3, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_22[] {
OC::SHARP_MZ,  // 26f5
OC::SHARP_MZ,  // 26f6
};
static_assert(std::size(oldCompRange_22) == 2, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_23[] {
OC::AQUARIUS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 2708
OC::NONE,  // 2709
OC::NONE,  // 270a
OC::NONE,  // 270b
OC::NONE,  // 270c
OC::NONE,  // 270d
OC::NONE,  // 270e
OC::NONE,  // 270f
OC::NONE,  // 2710
OC::NONE,  // 2711
OC::NONE,  // 2712
OC::AMSTRAD_CPC | OC::APPLE | OC::ATARI_ST | OC::COMMODORE | OC::TANDY_TRS80,  // 2713
};
static_assert(std::size(oldCompRange_23) == 12, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_24[] {
OC::MSX,  // 27ca
};
static_assert(std::size(oldCompRange_24) == 1, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_25[] {
OC::SHARP_MZ,  // 29b6
};
static_assert(std::size(oldCompRange_25) == 1, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_26[] {
OC::SHARP_MZ,  // 29c9
OC::NONE,  // 29ca
OC::OHIO_SCIENTIFIC,  // 29cb
};
static_assert(std::size(oldCompRange_26) == 3, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_27[] {
OC::AMSTRAD_CPC,  // 2b1c
OC::NONE,  // 2b1d
OC::NONE,  // 2b1e
OC::NONE,  // 2b1f
OC::NONE,  // 2b20
OC::NONE,  // 2b21
OC::NONE,  // 2b22
OC::NONE,  // 2b23
OC::AQUARIUS | OC::SHARP_MZ,  // 2b24
};
static_assert(std::size(oldCompRange_27) == 9, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_28[] {
OC::AMSTRAD_CPC | OC::TELETEXT,  // 2b60
OC::AMSTRAD_CPC | OC::TELETEXT,  // 2b61
OC::AMSTRAD_CPC | OC::TELETEXT,  // 2b62
OC::AMSTRAD_CPC | OC::TELETEXT,  // 2b63
OC::AMSTRAD_CPC,  // 2b64
OC::AMSTRAD_CPC,  // 2b65
};
static_assert(std::size(oldCompRange_28) == 6, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_29[] {
OC::SHARP_MZ,  // 2bba
};
static_assert(std::size(oldCompRange_29) == 1, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_30[] {
OC::SHARP_MZ,  // 1cc00
OC::SHARP_MZ,  // 1cc01
OC::SHARP_MZ,  // 1cc02
OC::SHARP_MZ,  // 1cc03
OC::SHARP_MZ,  // 1cc04
OC::SHARP_MZ,  // 1cc05
OC::SHARP_MZ,  // 1cc06
OC::SHARP_MZ,  // 1cc07
OC::SHARP_MZ,  // 1cc08
OC::SHARP_MZ,  // 1cc09
OC::SHARP_MZ,  // 1cc0a
OC::SHARP_MZ,  // 1cc0b
OC::SHARP_MZ,  // 1cc0c
OC::SHARP_MZ,  // 1cc0d
OC::SHARP_MZ,  // 1cc0e
OC::SHARP_MZ,  // 1cc0f
OC::SHARP_MZ,  // 1cc10
OC::SHARP_MZ,  // 1cc11
OC::SHARP_MZ,  // 1cc12
OC::SHARP_MZ,  // 1cc13
OC::SHARP_MZ,  // 1cc14
OC::SHARP_MZ,  // 1cc15
OC::SHARP_MZ,  // 1cc16
OC::SHARP_MZ,  // 1cc17
OC::SHARP_MZ,  // 1cc18
OC::SHARP_MZ,  // 1cc19
OC::SHARP_MZ,  // 1cc1a
OC::SHARP_MZ,  // 1cc1b
OC::SHARP_MZ,  // 1cc1c
OC::SHARP_MZ,  // 1cc1d
OC::SHARP_MZ,  // 1cc1e
OC::SHARP_MZ,  // 1cc1f
OC::SHARP_MZ,  // 1cc20
OC::SHARP_MZ,  // 1cc21
OC::SHARP_MZ,  // 1cc22
OC::SHARP_MZ,  // 1cc23
OC::SHARP_MZ,  // 1cc24
OC::SHARP_MZ,  // 1cc25
OC::SHARP_MZ,  // 1cc26
OC::SHARP_MZ,  // 1cc27
OC::SHARP_MZ,  // 1cc28
OC::SHARP_MZ,  // 1cc29
OC::SHARP_MZ,  // 1cc2a
OC::SHARP_MZ,  // 1cc2b
OC::SHARP_MZ,  // 1cc2c
OC::SHARP_MZ,  // 1cc2d
OC::SHARP_MZ,  // 1cc2e
OC::SHARP_MZ,  // 1cc2f
OC::SHARP_MZ,  // 1cc30
OC::SHARP_MZ,  // 1cc31
OC::SHARP_MZ,  // 1cc32
OC::SHARP_MZ,  // 1cc33
OC::SHARP_MZ,  // 1cc34
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc35
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc36
OC::SHARP_MZ,  // 1cc37
OC::SHARP_MZ,  // 1cc38
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc39
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc3a
OC::SHARP_MZ,  // 1cc3b
OC::SHARP_MZ,  // 1cc3c
OC::SHARP_MZ,  // 1cc3d
OC::SHARP_MZ,  // 1cc3e
OC::SHARP_MZ,  // 1cc3f
OC::SHARP_MZ,  // 1cc40
OC::SHARP_MZ,  // 1cc41
OC::SHARP_MZ,  // 1cc42
OC::SHARP_MZ,  // 1cc43
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc44
OC::SHARP_MZ | OC::ROBOTRON,  // 1cc45
OC::SHARP_MZ,  // 1cc46
OC::SHARP_MZ,  // 1cc47
OC::SHARP_MZ,  // 1cc48
OC::SHARP_MZ,  // 1cc49
OC::SHARP_MZ,  // 1cc4a
OC::SHARP_MZ,  // 1cc4b
OC::SHARP_MZ,  // 1cc4c
OC::SHARP_MZ,  // 1cc4d
OC::SHARP_MZ,  // 1cc4e
OC::SHARP_MZ,  // 1cc4f
OC::SHARP_MZ,  // 1cc50
OC::SHARP_MZ,  // 1cc51
OC::SHARP_MZ,  // 1cc52
OC::SHARP_MZ,  // 1cc53
OC::SHARP_MZ,  // 1cc54
OC::SHARP_MZ,  // 1cc55
OC::SHARP_MZ,  // 1cc56
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1cc57
OC::SHARP_MZ,  // 1cc58
OC::SHARP_MZ,  // 1cc59
OC::SHARP_MZ,  // 1cc5a
OC::SHARP_MZ,  // 1cc5b
OC::SHARP_MZ,  // 1cc5c
OC::SHARP_MZ,  // 1cc5d
OC::SHARP_MZ,  // 1cc5e
OC::SHARP_MZ,  // 1cc5f
OC::SHARP_MZ,  // 1cc60
OC::SHARP_MZ,  // 1cc61
OC::SHARP_MZ,  // 1cc62
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1cc63
OC::AMSTRAD_CPC,  // 1cc64
OC::SHARP_MZ,  // 1cc65
OC::SHARP_MZ,  // 1cc66
OC::SHARP_MZ,  // 1cc67
OC::SHARP_MZ,  // 1cc68
OC::SHARP_MZ,  // 1cc69
OC::SHARP_MZ,  // 1cc6a
OC::SHARP_MZ,  // 1cc6b
OC::SHARP_MZ,  // 1cc6c
OC::SHARP_MZ,  // 1cc6d
OC::SHARP_MZ,  // 1cc6e
OC::SHARP_MZ,  // 1cc6f
OC::SHARP_MZ,  // 1cc70
OC::SHARP_MZ,  // 1cc71
OC::SHARP_MZ,  // 1cc72
OC::SHARP_MZ,  // 1cc73
OC::SHARP_MZ,  // 1cc74
OC::SHARP_MZ,  // 1cc75
OC::SHARP_MZ,  // 1cc76
OC::SHARP_MZ,  // 1cc77
OC::SHARP_MZ,  // 1cc78
OC::SHARP_MZ,  // 1cc79
OC::SHARP_MZ,  // 1cc7a
OC::SHARP_MZ,  // 1cc7b
OC::SHARP_MZ,  // 1cc7c
OC::SHARP_MZ,  // 1cc7d
OC::SHARP_MZ,  // 1cc7e
OC::SHARP_MZ,  // 1cc7f
OC::SHARP_MZ,  // 1cc80
OC::SHARP_MZ,  // 1cc81
OC::SHARP_MZ,  // 1cc82
OC::SHARP_MZ,  // 1cc83
OC::SHARP_MZ,  // 1cc84
OC::SHARP_MZ,  // 1cc85
OC::SHARP_MZ,  // 1cc86
OC::SHARP_MZ,  // 1cc87
OC::SHARP_MZ,  // 1cc88
OC::SHARP_MZ,  // 1cc89
OC::SHARP_MZ,  // 1cc8a
OC::OHIO_SCIENTIFIC,  // 1cc8b
OC::SHARP_MZ,  // 1cc8c
OC::ROBOTRON,  // 1cc8d
OC::ROBOTRON,  // 1cc8e
OC::ROBOTRON,  // 1cc8f
OC::SHARP_MZ,  // 1cc90
OC::SHARP_MZ,  // 1cc91
OC::SHARP_MZ,  // 1cc92
OC::SHARP_MZ,  // 1cc93
OC::SHARP_MZ,  // 1cc94
OC::SHARP_MZ,  // 1cc95
OC::SHARP_MZ,  // 1cc96
OC::SHARP_MZ,  // 1cc97
OC::SHARP_MZ,  // 1cc98
OC::SHARP_MZ,  // 1cc99
OC::SHARP_MZ,  // 1cc9a
OC::ROBOTRON,  // 1cc9b
OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1cc9c
OC::OHIO_SCIENTIFIC,  // 1cc9d
OC::SHARP_MZ,  // 1cc9e
OC::SHARP_MZ,  // 1cc9f
OC::SHARP_MZ,  // 1cca0
OC::SHARP_MZ,  // 1cca1
OC::SHARP_MZ,  // 1cca2
OC::SHARP_MZ,  // 1cca3
OC::SHARP_MZ,  // 1cca4
OC::SHARP_MZ,  // 1cca5
OC::SHARP_MZ,  // 1cca6
OC::SHARP_MZ,  // 1cca7
OC::SHARP_MZ,  // 1cca8
OC::SHARP_MZ,  // 1cca9
OC::SHARP_MZ,  // 1ccaa
OC::SHARP_MZ,  // 1ccab
OC::SHARP_MZ,  // 1ccac
OC::SHARP_MZ,  // 1ccad
OC::SHARP_MZ,  // 1ccae
OC::SHARP_MZ,  // 1ccaf
OC::SHARP_MZ,  // 1ccb0
OC::SHARP_MZ,  // 1ccb1
OC::SHARP_MZ,  // 1ccb2
OC::SHARP_MZ,  // 1ccb3
OC::SHARP_MZ,  // 1ccb4
OC::SHARP_MZ,  // 1ccb5
OC::SHARP_MZ,  // 1ccb6
OC::SHARP_MZ,  // 1ccb7
OC::SHARP_MZ,  // 1ccb8
OC::SHARP_MZ,  // 1ccb9
OC::SHARP_MZ,  // 1ccba
OC::SHARP_MZ,  // 1ccbb
OC::SHARP_MZ,  // 1ccbc
OC::SHARP_MZ,  // 1ccbd
OC::SHARP_MZ,  // 1ccbe
OC::SHARP_MZ,  // 1ccbf
OC::SHARP_MZ,  // 1ccc0
OC::SHARP_MZ,  // 1ccc1
OC::SHARP_MZ,  // 1ccc2
OC::SHARP_MZ,  // 1ccc3
OC::SHARP_MZ,  // 1ccc4
OC::SHARP_MZ,  // 1ccc5
OC::SHARP_MZ,  // 1ccc6
OC::SHARP_MZ,  // 1ccc7
OC::SHARP_MZ,  // 1ccc8
OC::SHARP_MZ,  // 1ccc9
OC::SHARP_MZ,  // 1ccca
OC::SHARP_MZ,  // 1cccb
OC::SHARP_MZ,  // 1cccc
OC::SHARP_MZ,  // 1cccd
OC::SHARP_MZ,  // 1ccce
OC::SHARP_MZ,  // 1cccf
OC::SHARP_MZ,  // 1ccd0
OC::SHARP_MZ,  // 1ccd1
OC::SHARP_MZ,  // 1ccd2
OC::SHARP_MZ,  // 1ccd3
OC::SHARP_MZ,  // 1ccd4
OC::SHARP_MZ,  // 1ccd5
OC::SHARP_MZ,  // 1ccd6
OC::SHARP_MZ,  // 1ccd7
OC::SHARP_MZ,  // 1ccd8
OC::SHARP_MZ,  // 1ccd9
OC::SHARP_MZ,  // 1ccda
OC::SHARP_MZ,  // 1ccdb
OC::SHARP_MZ,  // 1ccdc
OC::SHARP_MZ,  // 1ccdd
OC::SHARP_MZ,  // 1ccde
OC::SHARP_MZ,  // 1ccdf
OC::SHARP_MZ,  // 1cce0
OC::SHARP_MZ,  // 1cce1
OC::SHARP_MZ,  // 1cce2
OC::SHARP_MZ,  // 1cce3
OC::SHARP_MZ,  // 1cce4
OC::SHARP_MZ,  // 1cce5
OC::SHARP_MZ,  // 1cce6
OC::SHARP_MZ,  // 1cce7
OC::SHARP_MZ,  // 1cce8
OC::SHARP_MZ,  // 1cce9
OC::SHARP_MZ,  // 1ccea
OC::SHARP_MZ,  // 1cceb
OC::SHARP_MZ,  // 1ccec
OC::SHARP_MZ,  // 1cced
OC::SHARP_MZ,  // 1ccee
OC::SHARP_MZ,  // 1ccef
OC::SHARP_MZ,  // 1ccf0
OC::SHARP_MZ,  // 1ccf1
OC::SHARP_MZ,  // 1ccf2
OC::SHARP_MZ,  // 1ccf3
OC::SHARP_MZ,  // 1ccf4
OC::SHARP_MZ,  // 1ccf5
OC::SHARP_MZ,  // 1ccf6
OC::SHARP_MZ,  // 1ccf7
OC::SHARP_MZ,  // 1ccf8
OC::SHARP_MZ,  // 1ccf9
OC::NONE,  // 1ccfa
OC::NONE,  // 1ccfb
OC::NONE,  // 1ccfc
OC::NONE,  // 1ccfd
OC::NONE,  // 1ccfe
OC::NONE,  // 1ccff
OC::KAYPRO,  // 1cd00
OC::KAYPRO,  // 1cd01
OC::KAYPRO,  // 1cd02
OC::KAYPRO,  // 1cd03
OC::KAYPRO,  // 1cd04
OC::KAYPRO,  // 1cd05
OC::KAYPRO,  // 1cd06
OC::KAYPRO,  // 1cd07
OC::KAYPRO,  // 1cd08
OC::KAYPRO,  // 1cd09
OC::KAYPRO,  // 1cd0a
OC::KAYPRO,  // 1cd0b
OC::KAYPRO,  // 1cd0c
OC::KAYPRO,  // 1cd0d
OC::KAYPRO,  // 1cd0e
OC::KAYPRO,  // 1cd0f
OC::KAYPRO,  // 1cd10
OC::KAYPRO,  // 1cd11
OC::KAYPRO,  // 1cd12
OC::KAYPRO,  // 1cd13
OC::KAYPRO,  // 1cd14
OC::KAYPRO,  // 1cd15
OC::KAYPRO,  // 1cd16
OC::KAYPRO,  // 1cd17
OC::KAYPRO,  // 1cd18
OC::KAYPRO,  // 1cd19
OC::KAYPRO,  // 1cd1a
OC::KAYPRO,  // 1cd1b
OC::KAYPRO,  // 1cd1c
OC::KAYPRO,  // 1cd1d
OC::KAYPRO,  // 1cd1e
OC::KAYPRO,  // 1cd1f
OC::KAYPRO,  // 1cd20
OC::KAYPRO,  // 1cd21
OC::KAYPRO,  // 1cd22
OC::KAYPRO,  // 1cd23
OC::KAYPRO,  // 1cd24
OC::KAYPRO,  // 1cd25
OC::KAYPRO,  // 1cd26
OC::KAYPRO,  // 1cd27
OC::KAYPRO,  // 1cd28
OC::KAYPRO,  // 1cd29
OC::KAYPRO,  // 1cd2a
OC::KAYPRO,  // 1cd2b
OC::KAYPRO,  // 1cd2c
OC::KAYPRO,  // 1cd2d
OC::KAYPRO,  // 1cd2e
OC::KAYPRO,  // 1cd2f
OC::KAYPRO,  // 1cd30
OC::KAYPRO,  // 1cd31
OC::KAYPRO,  // 1cd32
OC::KAYPRO,  // 1cd33
OC::KAYPRO,  // 1cd34
OC::KAYPRO,  // 1cd35
OC::KAYPRO,  // 1cd36
OC::KAYPRO,  // 1cd37
OC::KAYPRO,  // 1cd38
OC::KAYPRO,  // 1cd39
OC::KAYPRO,  // 1cd3a
OC::KAYPRO,  // 1cd3b
OC::KAYPRO,  // 1cd3c
OC::KAYPRO,  // 1cd3d
OC::KAYPRO,  // 1cd3e
OC::KAYPRO,  // 1cd3f
OC::KAYPRO,  // 1cd40
OC::KAYPRO,  // 1cd41
OC::KAYPRO,  // 1cd42
OC::KAYPRO,  // 1cd43
OC::KAYPRO,  // 1cd44
OC::KAYPRO,  // 1cd45
OC::KAYPRO,  // 1cd46
OC::KAYPRO,  // 1cd47
OC::KAYPRO,  // 1cd48
OC::KAYPRO,  // 1cd49
OC::KAYPRO,  // 1cd4a
OC::KAYPRO,  // 1cd4b
OC::KAYPRO,  // 1cd4c
OC::KAYPRO,  // 1cd4d
OC::KAYPRO,  // 1cd4e
OC::KAYPRO,  // 1cd4f
OC::KAYPRO,  // 1cd50
OC::KAYPRO,  // 1cd51
OC::KAYPRO,  // 1cd52
OC::KAYPRO,  // 1cd53
OC::KAYPRO,  // 1cd54
OC::KAYPRO,  // 1cd55
OC::KAYPRO,  // 1cd56
OC::KAYPRO,  // 1cd57
OC::KAYPRO,  // 1cd58
OC::KAYPRO,  // 1cd59
OC::KAYPRO,  // 1cd5a
OC::KAYPRO,  // 1cd5b
OC::KAYPRO,  // 1cd5c
OC::KAYPRO,  // 1cd5d
OC::KAYPRO,  // 1cd5e
OC::KAYPRO,  // 1cd5f
OC::KAYPRO,  // 1cd60
OC::KAYPRO,  // 1cd61
OC::KAYPRO,  // 1cd62
OC::KAYPRO,  // 1cd63
OC::KAYPRO,  // 1cd64
OC::KAYPRO,  // 1cd65
OC::KAYPRO,  // 1cd66
OC::KAYPRO,  // 1cd67
OC::KAYPRO,  // 1cd68
OC::KAYPRO,  // 1cd69
OC::KAYPRO,  // 1cd6a
OC::KAYPRO,  // 1cd6b
OC::KAYPRO,  // 1cd6c
OC::KAYPRO,  // 1cd6d
OC::KAYPRO,  // 1cd6e
OC::KAYPRO,  // 1cd6f
OC::KAYPRO,  // 1cd70
OC::KAYPRO,  // 1cd71
OC::KAYPRO,  // 1cd72
OC::KAYPRO,  // 1cd73
OC::KAYPRO,  // 1cd74
OC::KAYPRO,  // 1cd75
OC::KAYPRO,  // 1cd76
OC::KAYPRO,  // 1cd77
OC::KAYPRO,  // 1cd78
OC::KAYPRO,  // 1cd79
OC::KAYPRO,  // 1cd7a
OC::KAYPRO,  // 1cd7b
OC::KAYPRO,  // 1cd7c
OC::KAYPRO,  // 1cd7d
OC::KAYPRO,  // 1cd7e
OC::KAYPRO,  // 1cd7f
OC::KAYPRO,  // 1cd80
OC::KAYPRO,  // 1cd81
OC::KAYPRO,  // 1cd82
OC::KAYPRO,  // 1cd83
OC::KAYPRO,  // 1cd84
OC::KAYPRO,  // 1cd85
OC::KAYPRO,  // 1cd86
OC::KAYPRO,  // 1cd87
OC::KAYPRO,  // 1cd88
OC::KAYPRO,  // 1cd89
OC::KAYPRO,  // 1cd8a
OC::KAYPRO,  // 1cd8b
OC::KAYPRO,  // 1cd8c
OC::KAYPRO,  // 1cd8d
OC::KAYPRO,  // 1cd8e
OC::KAYPRO,  // 1cd8f
OC::KAYPRO,  // 1cd90
OC::KAYPRO,  // 1cd91
OC::KAYPRO,  // 1cd92
OC::KAYPRO,  // 1cd93
OC::KAYPRO,  // 1cd94
OC::KAYPRO,  // 1cd95
OC::KAYPRO,  // 1cd96
OC::KAYPRO,  // 1cd97
OC::KAYPRO,  // 1cd98
OC::KAYPRO,  // 1cd99
OC::KAYPRO,  // 1cd9a
OC::KAYPRO,  // 1cd9b
OC::KAYPRO,  // 1cd9c
OC::KAYPRO,  // 1cd9d
OC::KAYPRO,  // 1cd9e
OC::KAYPRO,  // 1cd9f
OC::KAYPRO,  // 1cda0
OC::KAYPRO,  // 1cda1
OC::KAYPRO,  // 1cda2
OC::KAYPRO,  // 1cda3
OC::KAYPRO,  // 1cda4
OC::KAYPRO,  // 1cda5
OC::KAYPRO,  // 1cda6
OC::KAYPRO,  // 1cda7
OC::KAYPRO,  // 1cda8
OC::KAYPRO,  // 1cda9
OC::KAYPRO,  // 1cdaa
OC::KAYPRO,  // 1cdab
OC::KAYPRO,  // 1cdac
OC::KAYPRO,  // 1cdad
OC::KAYPRO,  // 1cdae
OC::KAYPRO,  // 1cdaf
OC::KAYPRO,  // 1cdb0
OC::KAYPRO,  // 1cdb1
OC::KAYPRO,  // 1cdb2
OC::KAYPRO,  // 1cdb3
OC::KAYPRO,  // 1cdb4
OC::KAYPRO,  // 1cdb5
OC::KAYPRO,  // 1cdb6
OC::KAYPRO,  // 1cdb7
OC::KAYPRO,  // 1cdb8
OC::KAYPRO,  // 1cdb9
OC::KAYPRO,  // 1cdba
OC::KAYPRO,  // 1cdbb
OC::KAYPRO,  // 1cdbc
OC::KAYPRO,  // 1cdbd
OC::KAYPRO,  // 1cdbe
OC::KAYPRO,  // 1cdbf
OC::KAYPRO,  // 1cdc0
OC::KAYPRO,  // 1cdc1
OC::KAYPRO,  // 1cdc2
OC::KAYPRO,  // 1cdc3
OC::KAYPRO,  // 1cdc4
OC::KAYPRO,  // 1cdc5
OC::KAYPRO,  // 1cdc6
OC::KAYPRO,  // 1cdc7
OC::KAYPRO,  // 1cdc8
OC::KAYPRO,  // 1cdc9
OC::KAYPRO,  // 1cdca
OC::KAYPRO,  // 1cdcb
OC::KAYPRO,  // 1cdcc
OC::KAYPRO,  // 1cdcd
OC::KAYPRO,  // 1cdce
OC::KAYPRO,  // 1cdcf
OC::KAYPRO,  // 1cdd0
OC::KAYPRO,  // 1cdd1
OC::KAYPRO,  // 1cdd2
OC::KAYPRO,  // 1cdd3
OC::KAYPRO,  // 1cdd4
OC::KAYPRO,  // 1cdd5
OC::KAYPRO,  // 1cdd6
OC::KAYPRO,  // 1cdd7
OC::KAYPRO,  // 1cdd8
OC::KAYPRO,  // 1cdd9
OC::KAYPRO,  // 1cdda
OC::KAYPRO,  // 1cddb
OC::KAYPRO,  // 1cddc
OC::KAYPRO,  // 1cddd
OC::KAYPRO,  // 1cdde
OC::KAYPRO,  // 1cddf
OC::KAYPRO,  // 1cde0
OC::KAYPRO,  // 1cde1
OC::KAYPRO,  // 1cde2
OC::KAYPRO,  // 1cde3
OC::KAYPRO,  // 1cde4
OC::KAYPRO,  // 1cde5
OC::AQUARIUS,  // 1cde6
OC::AQUARIUS,  // 1cde7
OC::AQUARIUS,  // 1cde8
OC::AQUARIUS,  // 1cde9
OC::AQUARIUS,  // 1cdea
OC::AQUARIUS,  // 1cdeb
OC::AQUARIUS,  // 1cdec
OC::AQUARIUS,  // 1cded
OC::AQUARIUS,  // 1cdee
OC::AQUARIUS,  // 1cdef
OC::AQUARIUS,  // 1cdf0
OC::AQUARIUS,  // 1cdf1
OC::AQUARIUS,  // 1cdf2
OC::AQUARIUS,  // 1cdf3
OC::AQUARIUS,  // 1cdf4
OC::AQUARIUS,  // 1cdf5
OC::AQUARIUS,  // 1cdf6
OC::AQUARIUS,  // 1cdf7
OC::AQUARIUS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1cdf8
OC::AQUARIUS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1cdf9
OC::OHIO_SCIENTIFIC,  // 1cdfa
OC::AQUARIUS,  // 1cdfb
OC::AQUARIUS,  // 1cdfc
OC::AQUARIUS,  // 1cdfd
OC::AQUARIUS,  // 1cdfe
OC::AQUARIUS,  // 1cdff
OC::OHIO_SCIENTIFIC,  // 1ce00
OC::OHIO_SCIENTIFIC,  // 1ce01
OC::OHIO_SCIENTIFIC,  // 1ce02
OC::OHIO_SCIENTIFIC,  // 1ce03
OC::OHIO_SCIENTIFIC,  // 1ce04
OC::OHIO_SCIENTIFIC,  // 1ce05
OC::OHIO_SCIENTIFIC,  // 1ce06
OC::OHIO_SCIENTIFIC,  // 1ce07
OC::OHIO_SCIENTIFIC,  // 1ce08
OC::OHIO_SCIENTIFIC,  // 1ce09
OC::OHIO_SCIENTIFIC,  // 1ce0a
OC::OHIO_SCIENTIFIC,  // 1ce0b
OC::OHIO_SCIENTIFIC,  // 1ce0c
OC::HP_TERMINAL,  // 1ce0d
OC::HP_TERMINAL,  // 1ce0e
OC::HP_TERMINAL,  // 1ce0f
OC::HP_TERMINAL,  // 1ce10
OC::HP_TERMINAL,  // 1ce11
OC::HP_TERMINAL,  // 1ce12
OC::HP_TERMINAL,  // 1ce13
OC::HP_TERMINAL,  // 1ce14
OC::HP_TERMINAL,  // 1ce15
OC::HP_TERMINAL,  // 1ce16
OC::HP_TERMINAL,  // 1ce17
OC::HP_TERMINAL,  // 1ce18
OC::HP_TERMINAL,  // 1ce19
OC::HP_TERMINAL,  // 1ce1a
OC::HP_TERMINAL,  // 1ce1b
OC::HP_TERMINAL,  // 1ce1c
OC::HP_TERMINAL,  // 1ce1d
OC::HP_TERMINAL,  // 1ce1e
OC::HP_TERMINAL,  // 1ce1f
OC::HP_TERMINAL,  // 1ce20
OC::HP_TERMINAL,  // 1ce21
OC::HP_TERMINAL,  // 1ce22
OC::HP_TERMINAL,  // 1ce23
OC::HP_TERMINAL,  // 1ce24
OC::HP_TERMINAL,  // 1ce25
OC::HP_TERMINAL,  // 1ce26
OC::HP_TERMINAL,  // 1ce27
OC::HP_TERMINAL,  // 1ce28
OC::HP_TERMINAL,  // 1ce29
OC::HP_TERMINAL,  // 1ce2a
OC::HP_TERMINAL,  // 1ce2b
OC::HP_TERMINAL,  // 1ce2c
OC::HP_TERMINAL,  // 1ce2d
OC::HP_TERMINAL,  // 1ce2e
OC::HP_TERMINAL,  // 1ce2f
OC::HP_TERMINAL,  // 1ce30
OC::HP_TERMINAL,  // 1ce31
OC::HP_TERMINAL,  // 1ce32
OC::HP_TERMINAL,  // 1ce33
OC::HP_TERMINAL,  // 1ce34
OC::HP_TERMINAL,  // 1ce35
OC::HP_TERMINAL,  // 1ce36
OC::HP_TERMINAL,  // 1ce37
OC::HP_TERMINAL,  // 1ce38
OC::HP_TERMINAL,  // 1ce39
OC::HP_TERMINAL,  // 1ce3a
OC::HP_TERMINAL,  // 1ce3b
OC::HP_TERMINAL,  // 1ce3c
OC::HP_TERMINAL,  // 1ce3d
OC::HP_TERMINAL,  // 1ce3e
OC::HP_TERMINAL,  // 1ce3f
OC::HP_TERMINAL,  // 1ce40
OC::HP_TERMINAL,  // 1ce41
OC::HP_TERMINAL,  // 1ce42
OC::HP_TERMINAL,  // 1ce43
OC::HP_TERMINAL,  // 1ce44
OC::HP_TERMINAL,  // 1ce45
OC::HP_TERMINAL,  // 1ce46
OC::HP_TERMINAL,  // 1ce47
OC::HP_TERMINAL,  // 1ce48
OC::HP_TERMINAL,  // 1ce49
OC::HP_TERMINAL,  // 1ce4a
OC::HP_TERMINAL,  // 1ce4b
OC::HP_TERMINAL,  // 1ce4c
OC::HP_TERMINAL,  // 1ce4d
OC::HP_TERMINAL,  // 1ce4e
OC::HP_TERMINAL,  // 1ce4f
OC::HP_TERMINAL,  // 1ce50
OC::TELETEXT,  // 1ce51
OC::TELETEXT,  // 1ce52
OC::TELETEXT,  // 1ce53
OC::TELETEXT,  // 1ce54
OC::TELETEXT,  // 1ce55
OC::TELETEXT,  // 1ce56
OC::TELETEXT,  // 1ce57
OC::TELETEXT,  // 1ce58
OC::TELETEXT,  // 1ce59
OC::TELETEXT,  // 1ce5a
OC::TELETEXT,  // 1ce5b
OC::TELETEXT,  // 1ce5c
OC::TELETEXT,  // 1ce5d
OC::TELETEXT,  // 1ce5e
OC::TELETEXT,  // 1ce5f
OC::TELETEXT,  // 1ce60
OC::TELETEXT,  // 1ce61
OC::TELETEXT,  // 1ce62
OC::TELETEXT,  // 1ce63
OC::TELETEXT,  // 1ce64
OC::TELETEXT,  // 1ce65
OC::TELETEXT,  // 1ce66
OC::TELETEXT,  // 1ce67
OC::TELETEXT,  // 1ce68
OC::TELETEXT,  // 1ce69
OC::TELETEXT,  // 1ce6a
OC::TELETEXT,  // 1ce6b
OC::TELETEXT,  // 1ce6c
OC::TELETEXT,  // 1ce6d
OC::TELETEXT,  // 1ce6e
OC::TELETEXT,  // 1ce6f
OC::TELETEXT,  // 1ce70
OC::TELETEXT,  // 1ce71
OC::TELETEXT,  // 1ce72
OC::TELETEXT,  // 1ce73
OC::TELETEXT,  // 1ce74
OC::TELETEXT,  // 1ce75
OC::TELETEXT,  // 1ce76
OC::TELETEXT,  // 1ce77
OC::TELETEXT,  // 1ce78
OC::TELETEXT,  // 1ce79
OC::TELETEXT,  // 1ce7a
OC::TELETEXT,  // 1ce7b
OC::TELETEXT,  // 1ce7c
OC::TELETEXT,  // 1ce7d
OC::TELETEXT,  // 1ce7e
OC::TELETEXT,  // 1ce7f
OC::TELETEXT,  // 1ce80
OC::TELETEXT,  // 1ce81
OC::TELETEXT,  // 1ce82
OC::TELETEXT,  // 1ce83
OC::TELETEXT,  // 1ce84
OC::TELETEXT,  // 1ce85
OC::TELETEXT,  // 1ce86
OC::TELETEXT,  // 1ce87
OC::TELETEXT,  // 1ce88
OC::TELETEXT,  // 1ce89
OC::TELETEXT,  // 1ce8a
OC::TELETEXT,  // 1ce8b
OC::TELETEXT,  // 1ce8c
OC::TELETEXT,  // 1ce8d
OC::TELETEXT,  // 1ce8e
OC::TELETEXT,  // 1ce8f
OC::ROBOTRON,  // 1ce90
OC::ROBOTRON,  // 1ce91
OC::ROBOTRON,  // 1ce92
OC::ROBOTRON,  // 1ce93
OC::ROBOTRON,  // 1ce94
OC::ROBOTRON,  // 1ce95
OC::ROBOTRON,  // 1ce96
OC::ROBOTRON,  // 1ce97
OC::ROBOTRON,  // 1ce98
OC::ROBOTRON,  // 1ce99
OC::ROBOTRON,  // 1ce9a
OC::ROBOTRON,  // 1ce9b
OC::ROBOTRON,  // 1ce9c
OC::ROBOTRON,  // 1ce9d
OC::ROBOTRON,  // 1ce9e
OC::ROBOTRON,  // 1ce9f
OC::ROBOTRON | OC::KAYPRO,  // 1cea0
OC::ROBOTRON,  // 1cea1
OC::ROBOTRON,  // 1cea2
OC::ROBOTRON | OC::KAYPRO,  // 1cea3
OC::ROBOTRON,  // 1cea4
OC::ROBOTRON,  // 1cea5
OC::ROBOTRON,  // 1cea6
OC::ROBOTRON,  // 1cea7
OC::ROBOTRON | OC::KAYPRO,  // 1cea8
OC::ROBOTRON,  // 1cea9
OC::ROBOTRON,  // 1ceaa
OC::ROBOTRON | OC::KAYPRO,  // 1ceab
OC::ROBOTRON,  // 1ceac
OC::ROBOTRON,  // 1cead
OC::ROBOTRON,  // 1ceae
OC::ROBOTRON,  // 1ceaf
OC::SMALLTALK,  // 1ceb0
OC::SMALLTALK,  // 1ceb1
OC::SMALLTALK,  // 1ceb2
OC::SMALLTALK,  // 1ceb3
};
static_assert(std::size(oldCompRange_30) == 692, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_31[] {
OC::KORVET,  // 1f15b
OC::NONE,  // 1f15c
OC::NONE,  // 1f15d
OC::NONE,  // 1f15e
OC::KORVET,  // 1f15f
};
static_assert(std::size(oldCompRange_31) == 5, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_32[] {
OC::SHARP_MZ,  // 1f172
OC::NONE,  // 1f173
OC::NONE,  // 1f174
OC::NONE,  // 1f175
OC::NONE,  // 1f176
OC::SHARP_MZ,  // 1f177
OC::NONE,  // 1f178
OC::NONE,  // 1f179
OC::NONE,  // 1f17a
OC::KORVET,  // 1f17b
OC::NONE,  // 1f17c
OC::NONE,  // 1f17d
OC::NONE,  // 1f17e
OC::KORVET,  // 1f17f
};
static_assert(std::size(oldCompRange_32) == 14, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_33[] {
OC::SHARP_MZ,  // 1f78f
OC::NONE,  // 1f790
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1f791
OC::NONE,  // 1f792
OC::SHARP_MZ,  // 1f793
};
static_assert(std::size(oldCompRange_33) == 5, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_34[] {
OC::ATARI_8BIT,  // 1f8b0
OC::TANDY_TRS80,  // 1f8b1
OC::SMALLTALK,  // 1f8b2
OC::SHARP_MZ,  // 1f8b3
OC::SHARP_MZ,  // 1f8b4
OC::SHARP_MZ,  // 1f8b5
OC::SMALLTALK | OC::SHARP_MZ,  // 1f8b6
OC::SHARP_MZ,  // 1f8b7
OC::OHIO_SCIENTIFIC,  // 1f8b8
OC::OHIO_SCIENTIFIC,  // 1f8b9
OC::OHIO_SCIENTIFIC,  // 1f8ba
OC::OHIO_SCIENTIFIC,  // 1f8bb
};
static_assert(std::size(oldCompRange_34) == 12, "Autotool failed");

constinit const Flags<uc::OldComp> oldCompRange_35[] {
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb00
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb01
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb02
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb03
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb04
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb05
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb06
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb07
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb08
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb09
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0a
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0b
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0c
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0d
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0e
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb0f
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb10
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb11
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb12
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb13
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb14
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb15
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb16
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb17
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb18
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb19
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1a
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1b
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1c
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1d
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1e
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb1f
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb20
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb21
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb22
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb23
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb24
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb25
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb26
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb27
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb28
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb29
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb2a
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb2b
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb2c
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::HP_TERMINAL,  // 1fb2d
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb2e
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb2f
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb30
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb31
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb32
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb33
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb34
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb35
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb36
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb37
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb38
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET | OC::HP_TERMINAL,  // 1fb39
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb3a
OC::AQUARIUS | OC::MINITEL | OC::ORIC | OC::TELETEXT | OC::TANDY_TRS80 | OC::TANDY_COCO | OC::KORVET,  // 1fb3b
OC::TELETEXT,  // 1fb3c
OC::TELETEXT,  // 1fb3d
OC::TELETEXT,  // 1fb3e
OC::TELETEXT,  // 1fb3f
OC::TELETEXT,  // 1fb40
OC::TELETEXT,  // 1fb41
OC::TELETEXT,  // 1fb42
OC::TELETEXT,  // 1fb43
OC::TELETEXT,  // 1fb44
OC::TELETEXT,  // 1fb45
OC::TELETEXT,  // 1fb46
OC::TELETEXT,  // 1fb47
OC::TELETEXT,  // 1fb48
OC::TELETEXT,  // 1fb49
OC::TELETEXT,  // 1fb4a
OC::TELETEXT,  // 1fb4b
OC::TELETEXT,  // 1fb4c
OC::TELETEXT,  // 1fb4d
OC::TELETEXT,  // 1fb4e
OC::TELETEXT,  // 1fb4f
OC::TELETEXT,  // 1fb50
OC::TELETEXT,  // 1fb51
OC::TELETEXT,  // 1fb52
OC::TELETEXT,  // 1fb53
OC::TELETEXT,  // 1fb54
OC::TELETEXT,  // 1fb55
OC::TELETEXT,  // 1fb56
OC::TELETEXT,  // 1fb57
OC::TELETEXT,  // 1fb58
OC::TELETEXT,  // 1fb59
OC::TELETEXT,  // 1fb5a
OC::TELETEXT,  // 1fb5b
OC::TELETEXT,  // 1fb5c
OC::TELETEXT,  // 1fb5d
OC::TELETEXT,  // 1fb5e
OC::TELETEXT,  // 1fb5f
OC::TELETEXT,  // 1fb60
OC::TELETEXT,  // 1fb61
OC::TELETEXT,  // 1fb62
OC::TELETEXT,  // 1fb63
OC::TELETEXT,  // 1fb64
OC::TELETEXT,  // 1fb65
OC::TELETEXT,  // 1fb66
OC::TELETEXT,  // 1fb67
OC::TELETEXT,  // 1fb68
OC::TELETEXT,  // 1fb69
OC::TELETEXT,  // 1fb6a
OC::TELETEXT,  // 1fb6b
OC::MSX | OC::TELETEXT,  // 1fb6c
OC::MSX | OC::TELETEXT,  // 1fb6d
OC::MSX | OC::TELETEXT,  // 1fb6e
OC::MSX | OC::TELETEXT,  // 1fb6f
OC::COMMODORE | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb70
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb71
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb72
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb73
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb74
OC::COMMODORE | OC::TELETEXT | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::KAYPRO,  // 1fb75
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb76
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb77
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb78
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb79
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb7a
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb7b
OC::APPLE | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fb7c
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fb7d
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fb7e
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fb7f
OC::APPLE,  // 1fb80
OC::APPLE,  // 1fb81
OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON | OC::KAYPRO,  // 1fb82
OC::COMMODORE | OC::OHIO_SCIENTIFIC,  // 1fb83
OC::COMMODORE | OC::OHIO_SCIENTIFIC,  // 1fb84
OC::MSX | OC::COMMODORE | OC::OHIO_SCIENTIFIC | OC::KAYPRO,  // 1fb85
OC::COMMODORE | OC::OHIO_SCIENTIFIC,  // 1fb86
OC::MSX | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fb87
OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb88
OC::COMMODORE,  // 1fb89
OC::MSX | OC::COMMODORE | OC::TANDY_TRS80,  // 1fb8a
OC::COMMODORE,  // 1fb8b
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::COMMODORE | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb8c
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb8d
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::SINCLAIR | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb8e
OC::AMSTRAD_CPC | OC::AQUARIUS | OC::COMMODORE | OC::SINCLAIR | OC::SHARP_MZ | OC::OHIO_SCIENTIFIC,  // 1fb8f
OC::APPLE | OC::COMMODORE | OC::SINCLAIR | OC::SHARP_MZ | OC::ROBOTRON,  // 1fb90
OC::COMMODORE | OC::SINCLAIR,  // 1fb91
OC::SINCLAIR,  // 1fb92
OC::NONE,  // 1fb93
OC::COMMODORE,  // 1fb94
OC::AMSTRAD_CPC | OC::COMMODORE,  // 1fb95
OC::MSX | OC::COMMODORE,  // 1fb96
OC::TANDY_TRS80,  // 1fb97
OC::MSX | OC::COMMODORE | OC::SHARP_MZ,  // 1fb98
OC::MSX | OC::COMMODORE | OC::SHARP_MZ,  // 1fb99
OC::MSX,  // 1fb9a
OC::MSX,  // 1fb9b
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1fb9c
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1fb9d
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1fb9e
OC::AMSTRAD_CPC | OC::SHARP_MZ,  // 1fb9f
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba0
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba1
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba2
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba3
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba4
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba5
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba6
OC::AMSTRAD_CPC | OC::MINITEL | OC::TELETEXT,  // 1fba7
OC::AMSTRAD_CPC | OC::MINITEL,  // 1fba8
OC::AMSTRAD_CPC | OC::MINITEL,  // 1fba9
OC::MINITEL,  // 1fbaa
OC::MINITEL,  // 1fbab
OC::MINITEL,  // 1fbac
OC::MINITEL,  // 1fbad
OC::AMSTRAD_CPC | OC::MINITEL,  // 1fbae
OC::MSX,  // 1fbaf
OC::APPLE,  // 1fbb0
OC::APPLE | OC::COMMODORE,  // 1fbb1
OC::APPLE,  // 1fbb2
OC::APPLE,  // 1fbb3
OC::APPLE,  // 1fbb4
OC::APPLE,  // 1fbb5
OC::APPLE,  // 1fbb6
OC::APPLE,  // 1fbb7
OC::APPLE,  // 1fbb8
OC::APPLE,  // 1fbb9
OC::APPLE,  // 1fbba
OC::APPLE,  // 1fbbb
OC::APPLE,  // 1fbbc
OC::ATARI_ST,  // 1fbbd
OC::ATARI_ST,  // 1fbbe
OC::ATARI_ST,  // 1fbbf
OC::RISC_OS,  // 1fbc0
OC::TANDY_TRS80,  // 1fbc1
OC::TANDY_TRS80,  // 1fbc2
OC::TANDY_TRS80,  // 1fbc3
OC::TANDY_TRS80,  // 1fbc4
OC::AMSTRAD_CPC | OC::TANDY_TRS80 | OC::SHARP_MZ,  // 1fbc5
OC::AMSTRAD_CPC,  // 1fbc6
OC::AMSTRAD_CPC,  // 1fbc7
OC::AMSTRAD_CPC,  // 1fbc8
OC::TANDY_TRS80,  // 1fbc9
OC::TANDY_TRS80,  // 1fbca
OC::TANDY_TRS80,  // 1fbcb
OC::TANDY_TRS80,  // 1fbcc
OC::TANDY_TRS80,  // 1fbcd
OC::HP_TERMINAL,  // 1fbce
OC::HP_TERMINAL,  // 1fbcf
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd0
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd1
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd2
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd3
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd4
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd5
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd6
OC::SHARP_MZ | OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbd7
OC::OHIO_SCIENTIFIC,  // 1fbd8
OC::OHIO_SCIENTIFIC,  // 1fbd9
OC::OHIO_SCIENTIFIC,  // 1fbda
OC::OHIO_SCIENTIFIC,  // 1fbdb
OC::ROBOTRON,  // 1fbdc
OC::ROBOTRON,  // 1fbdd
OC::ROBOTRON,  // 1fbde
OC::ROBOTRON,  // 1fbdf
OC::ROBOTRON,  // 1fbe0
OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbe1
OC::ROBOTRON,  // 1fbe2
OC::OHIO_SCIENTIFIC | OC::ROBOTRON,  // 1fbe3
OC::OHIO_SCIENTIFIC,  // 1fbe4
OC::OHIO_SCIENTIFIC,  // 1fbe5
OC::OHIO_SCIENTIFIC | OC::KAYPRO,  // 1fbe6
OC::OHIO_SCIENTIFIC | OC::KAYPRO,  // 1fbe7
OC::AQUARIUS | OC::SHARP_MZ,  // 1fbe8
OC::AQUARIUS | OC::SHARP_MZ,  // 1fbe9
OC::AQUARIUS | OC::SHARP_MZ,  // 1fbea
OC::AQUARIUS | OC::SHARP_MZ,  // 1fbeb
OC::AQUARIUS,  // 1fbec
OC::AQUARIUS,  // 1fbed
OC::AQUARIUS,  // 1fbee
OC::AQUARIUS,  // 1fbef
OC::ATARI_ST,  // 1fbf0
OC::ATARI_ST,  // 1fbf1
OC::ATARI_ST,  // 1fbf2
OC::ATARI_ST,  // 1fbf3
OC::ATARI_ST,  // 1fbf4
OC::ATARI_ST,  // 1fbf5
OC::ATARI_ST,  // 1fbf6
OC::ATARI_ST,  // 1fbf7
OC::ATARI_ST,  // 1fbf8
OC::ATARI_ST,  // 1fbf9
};
static_assert(std::size(oldCompRange_35) == 250, "Autotool failed");

constinit const uc::OldCompSpan uc::oldCompSpans[] {
{ .span = oldCompRange_0, .firstCp = 0x2c6},
{ .span = oldCompRange_1, .firstCp = 0x2013},
{ .span = oldCompRange_2, .firstCp = 0x2070},
{ .span = oldCompRange_3, .firstCp = 0x20a0},
{ .span = oldCompRange_4, .firstCp = 0x2105},
{ .span = oldCompRange_5, .firstCp = 0x211e},
{ .span = oldCompRange_6, .firstCp = 0x2153},
{ .span = oldCompRange_7, .firstCp = 0x2190},
{ .span = oldCompRange_8, .firstCp = 0x21d0},
{ .span = oldCompRange_9, .firstCp = 0x21e6},
{ .span = oldCompRange_10, .firstCp = 0x2202},
{ .span = oldCompRange_11, .firstCp = 0x2260},
{ .span = oldCompRange_12, .firstCp = 0x2295},
{ .span = oldCompRange_13, .firstCp = 0x2301},
{ .span = oldCompRange_14, .firstCp = 0x237b},
{ .span = oldCompRange_15, .firstCp = 0x23ae},
{ .span = oldCompRange_16, .firstCp = 0x23e9},
{ .span = oldCompRange_17, .firstCp = 0x2400},
{ .span = oldCompRange_18, .firstCp = 0x2500},
{ .span = oldCompRange_19, .firstCp = 0x2639},
{ .span = oldCompRange_20, .firstCp = 0x265f},
{ .span = oldCompRange_21, .firstCp = 0x26aa},
{ .span = oldCompRange_22, .firstCp = 0x26f5},
{ .span = oldCompRange_23, .firstCp = 0x2708},
{ .span = oldCompRange_24, .firstCp = 0x27ca},
{ .span = oldCompRange_25, .firstCp = 0x29b6},
{ .span = oldCompRange_26, .firstCp = 0x29c9},
{ .span = oldCompRange_27, .firstCp = 0x2b1c},
{ .span = oldCompRange_28, .firstCp = 0x2b60},
{ .span = oldCompRange_29, .firstCp = 0x2bba},
{ .span = oldCompRange_30, .firstCp = 0x1cc00},
{ .span = oldCompRange_31, .firstCp = 0x1f15b},
{ .span = oldCompRange_32, .firstCp = 0x1f172},
{ .span = oldCompRange_33, .firstCp = 0x1f78f},
{ .span = oldCompRange_34, .firstCp = 0x1f8b0},
{ .span = oldCompRange_35, .firstCp = 0x1fb00},
};
static_assert(std::size(uc::oldCompSpans) == uc::N_OLDCOMP_SPANS, "Autotool failed");
